### ISSUE TITLE
graph DB alternative to neo4j

### ISSUE THREAD

**Issue by flosse** [kartevonmorgen/openfairdb#11]
#10 is one of the reasons to look for an alternative graph DB.

Do you know a good one?

**Comment by flosse** [comment]
#65 is a concrete proposal

**Comment by ourconomy** [comment]
Hi Markus,
I cannot contribute much to the decision about the change. However, when
the functionality of my specification proposals 

https://github.com/flosse/openfairdb/issues/64 
https://github.com/flosse/openfairdb/issues/53 

is used by users then a database is useful that can work well with a
large number of recursive requests.

Does it matter? Could we switch back to a graph database once volume
goes up?

My 2ct,
Oliver

**Comment by flosse** [comment]
> a database is useful that can work well with a large number of recursive requests. Does it matter?

At the moment it doesn't matter at all. It will take some time until we really need to talk about performance ;-)

> Could we switch back to a graph database once volume goes up? 

Sure :)

**Comment by flosse** [comment]
I close this in favor of #65
