### ISSUE TITLE
Use strsim (Levenshtein distance)

### ISSUE THREAD

**Issue by flosse** [kartevonmorgen/openfairdb#110]
The [strsim](https://crates.io/crates/strsim) crate provides e.g. the levenshtein algorithm.

Levenshtein distance https://en.wikipedia.org/wiki/Levenshtein_distance

**Comment by david-ziegler** [comment]
👍 
you mean for duplicate detection, right?

**Comment by flosse** [comment]
> you mean for duplicate detection, right?

yes and beside that we might could use it within the search algorithm!?

**Comment by david-ziegler** [comment]
that would be cool! we just have to see how fast it is... search performance shouldn't drop too much...

**Comment by uklotzde** [comment]
Now that a full-text search engine is used this issue has become obsolete.
