### ISSUE TITLE
GET /categories/{id} returns invalid JSON

### ISSUE THREAD

**Issue by sebokopter** [kartevonmorgen/openfairdb#115]
If you query a specific category with like e.g. `/categories/2cd00bebec0c48ba9db761da48678134` you get invalid JSON as a response. The quotes are escaped but they shouldn't.

Here is the response (from a query with [httpie](https://httpie.org/)):
```
$ http https://api.ofdb.io/v0/categories/2cd00bebec0c48ba9db761da48678134
HTTP/1.1 200 OK
Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 111
Content-Type: application/json
Date: Thu, 01 Nov 2018 12:32:47 GMT
Server: nginx/1.12.2

"{\"id\":\"2cd00bebec0c48ba9db761da48678134\",\"created\":1448792571276,\"version\":1,\"name\":\"Initiative\"}"
```

I would expect that the JSON is not escaped like it is done for `/categories` (without id):
```
$ http https://api.ofdb.io/v0/categories
HTTP/1.1 200 OK
Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 291
Content-Type: application/json
Date: Thu, 01 Nov 2018 12:38:52 GMT
Server: nginx/1.12.2

[
    {
        "created": 1448792571276,
        "id": "2cd00bebec0c48ba9db761da48678134",
        "name": "Initiative",
        "version": 1
    },
    {
        "created": 1448792571276,
        "id": "c2dc278a2d6a4b9b8a50cb606fc017ed",
        "name": "Event",
        "version": 1
    },
    {
        "created": 1448792571276,
        "id": "77b3c33a92554bcf8e8c2c86cedd6f6f",
        "name": "Unternehmen",
        "version": 1
    }
]
```

**Comment by uklotzde** [comment]
An intermediate conversion to string and then to JSON causes the escaping of string literals.

The corresponding GET method violates the REST principles by allowing to search for multiple IDs within the path, which mixes up two different use cases. Moreover it returns either a single object or an array of objects depending on the result. That's confusing, inconvenient, and should be avoided.

Searching for multiple entities should be split into a separate POST action.

`GET /categories/<id>`
Returns a single object or 404

`POST /categories/actions/search?id=<comma-separated list of ids>`
Returns a (possibly empty) array of objects, i.e. none or partial results are not an error
