### ISSUE TITLE
Return JSON Content-Type for error messages

### ISSUE THREAD

**Issue by sebokopter** [kartevonmorgen/openfairdb#116]
To be able to easily parse error messages it might be a good idea to return errors also as JSON Content-Type.
Currently you only get `text/html` as response Content-Type (at least for 404 status code). I would expect when I set `Accept: application/json` to also get a json error message.

**Comment by almereyda** [comment]
Using content negotiation would also be favouralbe for all other possible requests to the service.

**Comment by uklotzde** [comment]
Problem Details for HTTP APIs: https://tools.ietf.org/html/rfc7807

**Comment by wellemut** [comment]
Problem solved in https://github.com/kartevonmorgen/openfairdb/pull/353

**Comment by wellemut** [comment]
Frontend issue to implement the feedback message for endusers: https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/171
