### ISSUE TITLE
Bbox isn't a parameter of EventQuery

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#128]
According to the API-documentation bbox is a parameter for `GET /events` but with `GET /events?bbox=50.58053884893913,9.13865089416504,50.601435682639,9.17336940765381` I get a 404 error. The `EventQuery` currently has only `tags` and `created_by` as parameters.

**Comment by flosse** [comment]
The event API isn't completely implemented within the development version. The next release will contain the full API implementation :)

**Comment by flosse** [comment]
done
