### ISSUE TITLE
Return meaningful error messages

### ISSUE THREAD

**Issue by flosse** [kartevonmorgen/openfairdb#134]
## Problem
Viele Menschen beschweren sich (und viele tun brechen frustriert ab ohne Rückmeldung zu geben) etwa wie folgt: ich habe einen Termin versucht einzugeben und es ging nicht, es kam die Fehlermeldung "bad request", das sagt mir nicht, was ich da falsch gemacht habe und ändern muß. Sowas darf nicht passieren, das schreckt die Leute total ab. Ich hab es dann aufgegeben.

## Solution
Error-Messanges is needed for
- Warning that a field is used wrong (which field contains an error)
- If a protected tag is used (only for events)

**Comment by uklotzde** [comment]
Duplicate of #116

**Comment by wellemut** [comment]
@uklotzde Was könnte getan werden, damit Nutzer verstehen, was sie falsch machen.

Kann das Backend statt "Bad Request" zielgenaue Rückmeldungen schicken, was falsch gemacht wird. Zumindest das Feld, was betroffen ist. Z.B. "Error in end date"

Oder liegt es am Frontend, das es die Fehler nicht anzeigt?

**Comment by uklotzde** [comment]
Someone needs to get familiar how to catch and return those errors properly and implement the required "Responder(s)": https://rocket.rs/v0.4/guide/responses/#errors

**Comment by wellemut** [comment]
Is the backend sending therse "Responders".
Or does it need to be implemented in the backend?

**Comment by wellemut** [comment]
After finishing refactoring, @navid-kalaei  would love to care about.

**Comment by wellemut** [comment]
@magdaddy 
Bespricht das mit @uklotzde und @flosse  bis zum Hackahton
Es braucht dazu unbedingt ein live Treffen in Slowtec

**Comment by magdaddy** [comment]
This is basically done and already in master, just has to be released.
