### ISSUE TITLE
Subscribing to a bbox doesn't work

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#149]
to reproduce:
- log in on kartevonmorgen.org
- click on "Über Änderungen auf dem Laufenden bleiben"
- click on the left on "abonnieren"
--> The server responds with 401 Unauthorized.

**Comment by flosse** [comment]
That is a problem with CORS problem that can be fixed with a clean nginx config.

**Comment by david-ziegler** [comment]
Now it worked to subscribe to a bbox on nightly...

**Comment by flosse** [comment]
I think we can't close this because the nightly config of nginx is different to the one of stable :-\

**Comment by david-ziegler** [comment]
ok, then we just check again once we deployed to production (in the next few days)

**Comment by flosse** [comment]
closed with the new server :)

**Comment by david-ziegler** [comment]
the problem still seems to exist: https://github.com/flosse/kartevonmorgen/issues/547

**Comment by flosse** [comment]
I just tried it again and it worked.
Could you try to clear the browser cache?

**Comment by david-ziegler** [comment]
it works for me too. let's see what Helmut says in flosse/kartevonmorgen#547
