### ISSUE TITLE
Return ratings in search results

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#152]
In order to solve [https://github.com/flosse/kartevonmorgen/issues/522](https://github.com/flosse/kartevonmorgen/issues/522) the API would have to change. Maybe like so:
`GET /search` returns an array of `{id, lat, lng}` objects at the moment. How about search returns everything that's needed to show the result list:
```
{
  id: String,
  lat: Number,
  lng: Number,
  title: String,
  description: String,
  tags: [ String ],
  categories: [ String ],
  total_rating: Number,
  ratings: {
    diversity: Number,
    renewable: Number,
    fairness: Number,
    humanity: Number,
    transparency: Number,
    solidarity: Number
  }
}
```
However, would this make the search much slower? Or do you have these values precomputed already?

Otherwise, we could have two calls, maybe `GET /search`, `GET /entryBlobs`.
What do you think?

BTW, at the moment we are doing these three calls for each search:
`GET /search` --> ids, `GET /entries/{ids}` --> entries, `GET /ratings/{ids}` --> ratings.

**Comment by uklotzde** [comment]
Internally the search() functions already loads the complete entries with both categories and tags (no ratings at the moment). I didn't notice that these details are actually thrown away when composing the response!!

At least all visible results should be returned with more detailed information. The ratings of visible results should be optional, controlled by an additional query parameter.

**Comment by uklotzde** [comment]
The new version on nightly returns additional properties in search results:
* title
* description
* categories[]
* tags[]
* avg_rating

TODO: Optionally we could also calculate and return the individual (average) ratings.

**Comment by uklotzde** [comment]
TODO: Add a query parameter to request the inclusion of individual ratings for each entry in search results.

**Comment by uklotzde** [comment]
Fixed and deployed on nightly, API docs are updated in #161. No additional options needed, we simply return everything for the time being.

```json
{
    "visible": [
        {
            "id": "4c20979fe0754e74875afa4308d73ce7",
            "lat": 48.720333561636664,
            "lng": 9.152239220753424,
            "title": "slowtec GmbH",
            "description": "Entwicklungsdienstleistungen für konsequent nachhaltige technische Open Source Lösungen sowie  Softwareentwicklung & Automatisierung von energie- und wasserautarken Systemen.",
            "categories": [
                "77b3c33a92554bcf8e8c2c86cedd6f6f"
            ],
            "tags": [
                "assoziativ",
                "ie-stationsidee",
                "ingenieurbüro",
                "initiativ-kolloquium2",
                "kartevonmorgen",
                "linux",
                "new-work",
                "open-source",
                "potentialentfaltung",
                "regelungstechnik",
                "regpis",
                "selbstgeführt",
                "smart-lowtec",
                "socent",
                "software",
                "sozialezukunft",
                "soziokratie",
                "teal-organization",
                "transforming-capitalism-lab",
                "urbane-landwirtschaft"
            ],
            "ratings": {
                "total": 1.25,
                "diversity": 2.0,
                "fairness": 0.0,
                "humanity": 2.0,
                "renewable": 1.5,
                "solidarity": 0.0,
                "transparency": 2.0
            }
        }
    ],
    "invisible": []
}
```

**Comment by uklotzde** [comment]
Done and merged.
