### ISSUE TITLE
Search: doesn't work with multiple categories

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#153]
This call returns no entries: https://nightly.ofdb.io/v0/search?text=&categories=77b3c33a92554bcf8e8c2c86cedd6f6f,2cd00bebec0c48ba9db761da48678134&bbox=52.115380503921806,12.553896903991701,52.75584715449732,13.658022880554201

while this call does return entries:
https://nightly.ofdb.io/v0/search?text=&categories=2cd00bebec0c48ba9db761da48678134&bbox=52.115380503921806,12.553896903991701,52.75584715449732,13.658022880554201

The only difference is that the first has two categories enabled. The expected result would be more entries than in the second call.

**Comment by uklotzde** [comment]
Multiple categories are currently filtered with _Must_ instead of _Should_. This can be changed easily.
