### ISSUE TITLE
Entries have multiple categories although they shouldn't

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#157]
I just thought the category-filter doesn't work but actually some entries returned from the server have multiple categories:
e.g. the entry with id=0ceca5f209574992b97865a2e9f47a94 has these categories:
[77b3c33a92554bcf8e8c2c86cedd6f6f,
77b3c33a92554bcf8e8c2c86cedd6f6f,
77b3c33a92554bcf8e8c2c86cedd6f6f,
77b3c33a92554bcf8e8c2c86cedd6f6f,
2cd00bebec0c48ba9db761da48678134,
2cd00bebec0c48ba9db761da48678134,
2cd00bebec0c48ba9db761da48678134]

That doesn't make sense (and messes up the category filtering in the frontend). An entry should be either a company or an initiative, not both.

**Comment by uklotzde** [comment]
The domain model internally allows to assign multiple categories to an entry. Restrictions for specific category combinations (i.e. CAT1 excludes CAT2) are currently not supported.

**Comment by uklotzde** [comment]
Results with duplicate categories were caused by a bug. The latest version of entry 0ceca5f209574992b97865a2e9f47a94 has category 2cd00bebec0c48ba9db761da48678134.
