### ISSUE TITLE
Error on Mac OS X

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#17]
error occurs in line 106 of main.rs: `let pool = r2d2::Pool::new(config, manager).unwrap();`
error-message: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InitializationError(())', ../src/libcore/result.rs:688`

OS: Mac OS X 10.11
Neo4J version 2.3.3

**Comment by flosse** [comment]
Did you try build the current master?

**Comment by david-ziegler** [comment]
Ah, the authentification that's necessary in Neo4J version 2.3.3 was the problem!
So, adding `dbms.security.auth_enabled=false` in neo4j.properties as described in the README.md solves the problem (I forgot to do that before...).
When I get `Listening on http://127.0.0.1:6767, Ctrl-C to shutdown server` it works, right?
