### ISSUE TITLE
Reset user password

### ISSUE THREAD

**Issue by uklotzde** [kartevonmorgen/openfairdb#170]
Implement the back-end service for  resetting user's password:
* Send an e-mail with a link to enter a new password
* Reset requests should expire after 24 hours

#### Request a new password
```
POST /users/request_password_reset
{
    "username_or_email": "<username-or-email-address>",
}
```

-> E-Mail with a _Kvm_ link that contains both the e-mail address and a `token` (comma-separated):
```
https://kartevonmorgen.org/#/?reset_password=<email>,<token>
```

#### Reset the existing password

```
POST /users/reset_password
{
    "username_or_email": "<username-or-email-address>",
    "token": "<token>",
    "new_password":"<new-password>"
}
```

**Comment by wellemut** [comment]
@regenduft  @uklotzde 
Den ganzen Registrierungsprozess finde ich unnötig kompliziert. Mein Vorschlag wäre folgender:

- Statt dem "Login" link schreiben wir "Abonnieren"
- Wer drauf klickt landet direkt auf dem Kartenausschnitt auswahl fenster.
- Dort gibt er seine Mailadresse an und klickt auf "abonnieren"
- Per Mail muss er sein abowunsch bestätigen
- Alle Änderungen bekommt er dann per Mail und in jeder Mail ganz unten gibt es einen Link "Abonnement beenden"

Das ist super simple zum bedienen und wir sparen uns das ganze einloggen und passwort resetten!!!! 
Man kann derzeit übrigens auch nichts abonnieren. Versucht es mal. bei mir hat es gestern nicht geklappt. Und es ist zukunftsfähiger, weil später nicht jeder, der was abonniert hat, gleichzeitig einen Account hat, mit dem er was macht. (Evtl. laufen die Accounts dann sowieso über wechange)

Am besten wäre natürlich, der Subscribe button wäre direkt auf der Karte, sodass man auch in Iframes abonnieren kann.

Was meint ihr?
@ziedavid @flosse

**Comment by regenduft** [comment]
@wellemut wenn keine sonstige Login-Funktionaltät gebraucht wird, volle Zustimmung.

Bei mir klappt abbonnieren. Aber vorgestern hatte flosse noch ein problem beim abonieren, danach hat er api.kartevonmorgen.org zu kartevonmorgen.org/api umgezogen, seitdem sollte es klappen.

**Comment by uklotzde** [comment]
Ok, then let's prioritize kartevonmorgen/kvmflows#4 and implement the password reset later.

Subscribing e-mails addresses without confirmation can be used to spam the server with invalid subscriptions. The confirmation link does not prevent this entirely, but is at least a hurdle for saboteurs.

**Comment by david-ziegler** [comment]
doing kartevonmorgen/kvmflows#4 first sounds like a good idea!

> The confirmation link does not prevent this entirely

How do you mean that? How could someone subscribe with an email-address that they don't have access to, if you need to confirm a confirmation email first?

**Comment by uklotzde** [comment]
Each subscription would immediately create an entry in the database that the server needs to respect whenever an entry is changed. It doesn't matter if the e-mail address actually exists or not!

Even with the confirmation it is possible to create many new users and fill up the database with spam that needs to be removed. But at least those users do not need to be considered for subscriptions until their e-mail address has been confirmed. Sending out e-mails is still a bottleneck and open issue!

**Comment by uklotzde** [comment]
E-Mails from our domain would be blacklisted and blocked in no time if we start to send out e-mails to non-existent e-mail addresses!!!

**Comment by regenduft** [comment]
these issues exist also with the current registration site (only that a human needs some more clicks to find the registration page,  but this would not prevent any spam-bot to register).

Solution would be a CAPTCHA which needs to be solved to create an abbonement. Could be combined with some kind of ip-blacklisting, if really necessary (but this is a problem for NAT / Proxy users, so may be better to rely on a CAPTCHA solution provided by some 3rd party that is experienced with captcha) anyway I do not want to use google captcha...
