### ISSUE TITLE
Email-format issue

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#172]
@regenduft hat geschrieben: "Bei einem Nutzer fügt gmx in die Automatischen Emails Kopfzeilen in den email-text hinzu. Offenbar erkennt gmx den Ende des Email-Kopfes nicht. Hat sich eventuell in die Leerzeile (oberhalb des Hallo,), die normalerweise den EMail-Kopf vom Email-Text trennt, ein Leerzeichen eingeschlichen?"

**Email-Text (Inhalt, nicht Header):**
```
Hallo,
folgender Eintrag der Karte von morgen wurde verändert:
Envelope-To: <earthfriend@gmx.de>
X-GMX-Antispam: 0 (Mail was not recognized as spam); Detail=V3;
X-Spam-Flag: NO
X-UI-Filterresults: notjunk:1;V03:K0:099p3Sl5/BI=:951qd5sFyE+xyOHQwooo1Nku/h
phpxbflKEaCDgZc0HFx6CmXGkFTGAC6RN57qnoHO3rObmdvNkPzLKeusFT0Xh5mePFkK1rzbZ
cgPEszpA25njQnu4a4NWdCQgwg4DyT958Q4RlC9IhMthSR+UAuyohX7oyH5bqLjaEtBXkCv8J
vLx8ShQRAvCOOVd9/qIcvJMhmYMUmogOg6ZVvkpvVkaLsjRjwA0IZD3jfPw5FuF2y6jKn+bRb
deSug672iC3kRlFAp5vb30KWJB8/JOnHp6yJ+KTeTvQqEe0x86gzQAPTLJfF+0ENc09gPVjYi
qMKv3dRElS51cGfSWX+8Bt0mwgc/mwiLbTWjoGsCJafrnVo0G3v3jrCHuMo02W+5WjAz1brG8
NZRJR9oahOp+L76c1eNpYPKZJof4VacLt80n0550PjBjleFjP28gBhu0JCCP5cT/H0dBTxuUC
o/8uFkztss8y+n6f1W7V7KYxb4C68pE6zQOtC0QJh9OXdZUbWgLoxe64ixPl7DowHAbqqvzgb
D9hVY59gD1LW3IBa4NUsl8w3nvSNNxRQ9m81UnLdm1kU0urGoWyE6UHYIr+TO1gOHobbCOyxg
ujV3l7mGaEoGVFpJkd+8EHc1gbXVvogov6Ibh0tZlSm5s+VBF380efgDNxMaCRdto0TVwM53m
G7YR7TQkq0n6TrM4zxgEfHqm31JDUJAKBt88lUmQMxSifrep6gJeQhRUVst1420xcb81MF3ov
dpLXo0cyUBIFVMcG9wbO+N2HAxSXEfiuf99hHVAvK7W1vU8YAB+MtT1qgw/StYgQM9ChotDQx
QCmaQze0wIoMzkg0b0ZWIChw7dMvaNVjXEtRNdA3bZFXT1c0NtpS7SdQ222SnQrr3x8tOsuJ2
9YvZ6jBEbcIul3/zyyHgVE8w9KtpIIzCbSeE8Tt8TVA8nomOYdvRGhRMZHcV7IuHQxKVTws7S
vDxtAlx4G4Lucc98q6dZKKbaYcuUgJCnXFkeN2e81NiHJ8LXNRt1XCnrfguQKg8/Mgwzlhp9Z
3tinXmalKaHpi4dx6/Pp3BaH3ZyLM4e92/qHn7ZMIZ+CMDI+FLjkNAXhs7nLLRKe5XIkHixBM
9vKooRxPENsACSAtgxaEy8fh9GilkoysMiOlTpWOzjrpWbhCFg2yfi3CfEJW+vwQ4KtFVIsnA
iGqDYPap69RYlZtTEgMh5K64HEkue47Ec8sqnHG5xkEMWz4NEeXsLu7ruE7FD+JBNuwRAby1U
/+WQAAX95a6R1q+Wi6NHeS6ScTM6UoLbBj26hSFKir9E6zuGCw9f8CkTD7bv6QV/Li/K2Ctht
sQr/YXDlFG4mdIq39gH/mr4GqE1/gbZnWR5aHw8VGv/WKZPxzM4bje4H3+aikqY5KUGkCZgxP
XP4SHFDcAiI6jOVs/lLYHIdtg1PPpowrcBMRZj7yo6bn3g1eQoDPAiaTclRlvvzP1dmqv3bkZ
ZxHAlQAeR/TxVQ9yFvEO8TAxkI572AvEYLyz0Qh9X0AomzB1ae5hym/bi3VQUv5jbNw/bsenC
wrNg7+IKl27le9ZVSp3i54EnJE+YKmj3Y1gQaDQTwNFLAQRtVLXFqf3oAG4KhVfgfEzty7d+m
iaqKhePRT83gIrUFauyI3lzYTRu47P6egkD+G6uRaOPlkcwcsL2REzcabsxvvNS5boREFli73
DjXez6AlqvHZ8tlSdA0s12F4yB5QH7uzeZMvoWPHU+Kc1dmAd28kawadhZuc+J7dbNYOkwRJ/
3N6XkZbTpwxJI5xaYzIS/CO1Y/5VTdmZGQ5eWON6Wkg7FZcjZ8987TJgqhXejYWbrNY+YC7Ne
9xok0plMZJNqAl45qFDJpeTzQaF0jq4BxphPiOVbz83Ly2n8n18uh34ohptSJM1vky+hPt6Bs
WTg9EAv5ZELlgXYPJ4G2DBWAjS91zkFFDKP0bt8wmZFrUwtzoe6oF3lOQpGB13J5KBGuB3/2y
BXUaACSB0y85bCNdtpSHcmNcxHj3tEmxl4IhOCvwswgo4eXOl3mDjvtcAc9qUC0UmxetPvnP9
pq5FULsKd/+M+uI+rqJKO01gYZ3F94ij96gM0d4Yp+6xcNZXSr1nGMOqVl88LJ9vqD1qAA7uc
RnHHjPzplIg+5EhBZ3BGiUasp1fWJMAZw4e3m/gotMJaOlUpY38Z5BA==
Gemeinschaftsgarten Johannstadt (Initiative)
Der Garten wird von allen, die mitmachen, gemeinsam gestaltet, je nachdem, was sie sich wünschen und was gebraucht wird.
Er ist offen für alle, die Lust haben, sich zu beteiligen, sich einfach im Grünen zu erholen oder Menschen zu treffen.
Tags: gartennetzwerk-dresden, gemeinschaftsgarten, permakultur, pocsummit, umweltbildung, urban-gardening
Adresse: Dürerstraße / Ecke Silbermannstraße, 01307 Dresden, 
Webseite: https://gg-joh.de/
Email-Adresse: kontakt@gg-joh.de
Telefon: 
Eintrag anschauen oder bearbeiten:
https://kartevonmorgen.org/#/?entry=e4fd083a035c452fbf356fc1461c2436
Du kannst dein Abonnement des Kartenbereichs abbestellen indem du dich auf https://kartevonmorgen.org einloggst.
euphorische Grüße
das Karte von morgen-Team
```

**Comment by Momanuel** [comment]
Hallo, 

hab mich gerade registriert und folgende Mail mit der Bitte zum Bestätigen erhalten.
Ich nutze web.de

_____________________________________________________________________________________

-8



Na du Weltverbesserer*,
Envelope-To: <manuelmolt@web.de>
X-UI-Filterresults: unknown:5;V03:K0:HGOP80d8zng=:e/GjgCIvAhVprEy72ABLDzYZTR
GBlmDTEzEDRb2LkgyoV2UHElfUwrGPFYHnzhBoLvSU700daJQe2fRX6vnsUjMUbpv3dE4Xo8h
HrJRWUdqiy7gSw3odbptGqE1/dfWYyzPEWfBgiE+JpmTT7LtWY2D2mJaRQFYIwuF85HxJIUF7
PwAcqxsm6Z8awyQOUq+56acwfpKfASMkVty59y/zoiGvLNUlUhMgKY+UKd2aCqFgPnuhaDR7e
S58Jmlj8W78TErAr7g/Up/KHC8PeEMZ+Uor0nd2gr13nU7dSXSwzoyQ8ruo4NSnGXxSkhY9HY
5wCeM5LyiGbdNesgxIxBt/Phn6DFrycoVZDF5hDnZrlVxDnK/wQ2Jn4UddELxPRozLpw9MEvc
UyiNhWmqLh+/R5fR4VsSKgkkOmaiusfw1v5HKt2HTGCK4vL0b9Dghvb8Tu0Wg9V04DL/YGAkF
yWq580BWIM1nZTCQc4OaXjCAZbbSE2dM2I0Bav1e9Me28qIguLko6leLQDy51TK7e0SjFmEcr
UhITWpF8PR72yeA5upzlKZpZNZ6Ihuc32EZRRr17bllTLPZmKSlqB0Xo/2k4e5tlgGzDoOfXA
oVqqe3/7MUojnLY09qcy3a2NBqeKfTTGkomGEvePHu2u38giLeaaur7va112ShgkSP9dnOsuS
E4GcyqFo8wVUSH+T0eOdQ5bJcgGzaFC2Wn8D0BbabrVDB+TdFRuDLw6+MvhVHUGuDB4AT0oOp
dFUXVhgwrHQZYUilHfyI+zDQKgMLRVdYG3UNIROr0duX8C+VmHzAvVwbmM7K0c4TRjOehzkmN
rUAE2dd1UKJBeC5MSDjjo76yzTBe1S9auSUdiM6LPXvM6CqSpT0tH1mDxmr1Z5/VZiRUpRtB8
uy6RMhFzIxvs7IG0AiY/KiALt2ex3TVx/qmuSyHHm5I+4Tt/2IcLxP7FCrqFcTMofCkfSkYLr
ONiR3asaKoMJ/KwQwV3v5aPqkEGSfyEACVzk/gd4DpojlG7gZuTSh6s8Gf5KioldBBdM5gLWR
B3EYAryOY8GVV4IihyebKX1Ztjl5nFvP/ZLuxa3I2BkLaaxOrprQ3vMdgPoJ0lwO0ahEm2YFA
22dTPylsPfvLVa8Z6KyTRfiiGHKaK/n/DjMUCrdn2dJBLRB7r07AWIA09YsLvornpotZkfe6v
6bnJVkROpQtQ0+uc4e8MJ+eK8NUV28F2qy0Q+0Kl/MVy8q5QfJ7Jbx+PC/TzBAkeTtzdf2bGY
tjwSXRsxgu/fcsHjyS7ZRT87AimzRRKvzOizF3EKkLEaix06bK3+aaZbMZsCeQHXNjYpMhVQy
p5jqit2PnklWDBwHLgBrp89sLmsjlJ1PubuaVnyE/1LvSFXWVDYK2ByAVcDjJjgu9RLctaIpt
y315d8KylgW+xHWHhKC91teiyVizXgSoC/7ql74mjig4OE2fYCea2Wtv5E9qknxC6JPoY6Xlo
c9D0Xag40mZkkY55sLor9qlW9NE3MDaUh5ONpkno3hILhuiu49DUFl7ADg4t4oFxQmz2SyBJ/
YvNOFbj616D+FIBN0GB2uZiCd0Zu1evmtP0BFFN8kIMZtK0nDFzBDGpa3IMbv6l0Ju1weOCe6
u5NKq5SnkikiukHufqV2ZkIqMErs2dympiP2GhwaVgZEX6LRQg/QrlPr0oGkAz/zO+YUy3MWY
D3MhrKZz3M0eA1fDC6xJ86L5EcV+w5sVCwAThjlXAgvhf1RTUq4o5+LnvHSRUU3loBUvknO1I
avy+N07no5AtRfzIHRqjGHnjspYf/IUtBXNGtyPOBVLdoUakUFD1QzkDt1IRLirP6mSfMhTz2
WIt8dSbdiPIfWT/LRQSwpGh2xmPs3Jc6beMezyCTcb/tx3qsQXztzsIrClxzRxL7q8ksxf3lx
YidrzFwPiPOYxkpSvPqwyEKd7r0DHagHPL1FanouVYMHXPLTimIglZasWoxdep1Pnn38aYgKt
pvU5wOB6/XlVY33qK3v+u37fyKrsqVFMWHOLGPzhzZFRFLMsuYnkl+mllpFYeZ++TGNUsHNYy
mIw6e4k733IE7yZU/gCxmL+qZ92vma9iRZOm28CuOUPqv/n9Ia2/gBFKkZcBTxwuRtVoUyZJ6
Ci0MbSCTGv31XyYsBZxAyC+xGUJ1V7vj0cghNf2RsGL5xkIsjf9t3+YeiAIjlJdru2R3viYTU
TMfDkHPl0yWMInVBnM0TujDHI9Dswwh97u5ngaeK9zgtts/YpfV6qzFEWwzo8xr9pnvhDmhUM
qoNalcS1kFbicMgx6ByAL43wpMxWSQ7nkiOlHMkxYLJQaWCKorxX5HI+95DlCpOXAbSs8jZE+
OS3FZGIBfaOiAkzC4EoMSnb/vkuLi/UFsIf8RsqwPsMPP99T4jNoTWyPAD2scp4d37beokors
eAfp2qfWzipGZzR+xMDQKWyPWv2YAMGmClmCnB+PiW+/+B0Q8SYFMSOkxhnpFR9P0vcndfynn
LGehrzVYPH1f3ef/BKIUnLvlxEc85JaARIEgqryowHw9fLvXEbtCNXp1jFB+Fsw/5k4Nr4CFr
wWoJHEODhTYJEQMAQNZ+ARrbuic5/ANG4CUDtuNOESA3raMR2h8hwVI0GIsz53x1wImPscfY0
NG5DJKDkGTn16HVzEMylgQcg3fP+94WofRKlTUE62664W1LAKqZscxiTyQjAestWOUY0dPsc4
oouPX7Ft2xoqlFFZJKFSg3mjL

wir freuen uns, dass du bei der Karte von morgen mit dabei bist!


Bitte bestätige deine Email-Adresse hier:

https://kartevonmorgen.org/#/?confirm_email=JiAQawn4tCPYy41j7sEstS7pTJsSPxABydq5RPGZ7HJJMAV4Hvhw9uKsbF818oYd6Rq


euphorische Grüße,

das Karte von morgen-Team

Weitere Hinweise und Tipps zur Nutzung, z.B. wie du interaktive Karten
per <iframe> auf deiner Webseite einbettest oder Papierkarten erstellst,
findest du hier: https://blog.vonmorgen.org

**Comment by wellemut** [comment]
We solve it via https://github.com/kartevonmorgen/openfairdb/issues/194

**Comment by wellemut** [comment]
Another Example of supid notification messanges

Hallo,

Envelope-To: <Hartmut>

X-Spam-Flag: NO

X-UI-Filterresults: notjunk:1;V03:K0:ICyc8OJaizc=:bywS/f1Nua8YMEozYLkiOO/COk

r9uvmKbUzQ7f/WGpzA42M0eCf+jByTthlIKgKyImLygyj5QMs59WlTHJHPJYnBLrTdRC0K2lE

HsB50d+4UnhZRxEoEI46pCZiGeBqVKYWHeyqucb6fC5wx0bjd3pH07Rj5n6Hi6Vlfnioboz66

g5Ye9jW04bzuHMfXEDe6Vh3s4H2LpDuXmRVF+nyBa8jLKlfrmOpKgEclqwCrMpqKqhgTENp0e

k8nGqXYFww3ElrHpZAwBvi/Y2Btgi028FwW3v/UzfMXr9BDxqCcNMQCL+yZKKgyJKeHvyiqZL

Hr5ZpUFoBrzSlGNCWfPyJivINKyaEjE3HsYFIoxMvPMqEtsIOKCqai7pmBDYVG/ix9mobNIsX

aLmQJMxqRNXmh/He0AfHdSRPKEn3tgM0aHPfaB9L5J2iHE3yVnmbg+eOVGfSDLHKsyS2iUyGx

vpWN3vZJKYj1tAM/n3e8vDdD4mBcxizlJaBUVsMB6cbSFEDTtzqpYOUnz8u5x4V4v+UHNzcAN

RJwN6xkGfJz5nq1Jnz6bD8mG4DGFQm1u3cw2B/HmdS3IBYvHFtFgWqNDfOp2oNk2BkCfgSJdQ

7H4l+vWBZgzS0PVTj28j9dWyhbQxhLkdpH2rWRybRfSmrUC4w/pmuvu8XpHAAiYxXlqd6G1r3

mdvbbkba5FzhCUzxccbS9MZhCYY+8rFsynh0EczxSMDYg6xUkHpnz14T2JYqKpVY5DRMWCTBn

9nK5+PidEQ+Ewy3Bke1j1+0XTJaCi21+E7xtClUnO+g7tKweXGrPcdh5oUati0hOJIq5nyOAm

xgXVJk0G2s+a1jUMZxLcgMMvRZxDGdzKZv1NJikCrH/iDA/dTnlQCbbXqkBjK9wZqnzmKiweY

v6pwV+Qy12z9FLdGAp7RX2xhImPA5G02KJP3x563UR4Js9ksVNTTm8ObzJNdBNW2rXPdDdmTk

U+bVUtGVDV9jIjL/iur72c9v03HrXCYH9Fnpf7vjUJu/62Gabnu1vwVHHTSympKv5+KHp3eI3

SqVYBWnX82jRfNT1/KFeah0PjLPF8Uzf9IG6zNfZDLuBK6YXRuAVNMsfcvFEuC9cfT0P1+yZg

o+xKQ8cIKmZj/kjjY9gAtp8CSihOrRbeNqJp0tK6mfFVdL/9u12g1DykQ3cJydXFntwiydJrU

jExmc6/TwQ85NS4ulWRv8HMuSk6OmteZGMny1y6npejoLAnlIE2443+SAdvBAzROekCKZrobO

rWw/ZGDdxGD/pAFR/3F348AX1CBHgOzTawi3EubPMCjofXdwpfilr/PpdOlg3OPPn2uWgU2Ut

/W06HSCVnvSG5CvH2B0gq5SCrP7IJ/NemG/KKaF8Kjh20DIVHu6FKI7Mc0GARioz3rdYK6Xbn

+lBLRUydWBS/8ZgCs7DiXmS6pEzEGfqfNLpc3E7cRsqe81Gro5q2mdoyglQ4F7dQwox2qzxRj

JcRvlO7TCvKFhPwByHn27hjOYWHBdBj8AHpWnuDHyhWmZOI/3CC4ITxXCKxWUh4G8oWyglfoL

kRSdn9BIlfd7WlMRMTaEAVqT8ire8RNlRD8ZLgDBc3dAQojZLsqHqTxKpyx/1ibsCT8Q8WQDT

ZTYR88u0Ys1tsOkoTGUQW062zlApHkfrDNul374sRDP6egMvgrMMp+6t9A0REaXDMDvghEunr

9UwTY5QaweKslsU8r3JjnG6aQVv2YmKj8DbhKqTzMVukITu+4BGLnZfynBCtcStZxqfVku3Ka

HCO0ekw6AKMgSzfTiQbj7/zb7Xf8tJ7JGHtpZebGalykgGrL2NooqsHJgexB3iGsh32icn/Jn

eoVPuFo+g2z+WX72eGn44hAMCJgQYOBn4FHP77oLvUL1abm96vR1cmScfQNX4cGf1mnWLUZTT

mWIn9fFC6BKE4aoKCBlUEuD+D7GNPNSlExko7G5Abjg+yneSmEXxNyd+GrBdOKrBOf8gQsyew

VwpuFlNsw6HvW8iszetePhIyla1KWzBBgTgG9ZOHEue+5bKGD6AE58kwY1HapTNodj3ksDjkB

gI2rLoP7/kiGfj4Q1Rswwlp0062bLPxxs9LLkXV9xHK/Cphl0H9KhfFKeWiWNHqcU2HgyR/8h

xOkwGhJinmIzTh1fmAN9Ko7ARlbieRxMSCAxY8X9GQDDB1lUX9Xs3VPm9zDtF0kkhNs+k01zZ

NsamdSvE3JzadW7VJWKEdGD4MTqDG4PHFr+tp++RgJZzjPX+svXpu2WT2Darx68qKqG8oaFqC

tZbBi17qJdyRaoVcLOcH6FYQbHv5pfjmnT4fMznMg3INl2KNW21gq8Yp531eQgbifoOFG8fT/

XtcJtw49DVxFKM3LecAkOGdLJ2lPhUatUrsy8sDRtlTjt+ba8iFK/HHOQEPZ7ssALgf46zMhz

tnaMQ5nP6TeDpTnAuvEg/kfBqTnJbBf6F28xVb/jJHL8R5UYx3A8/3QsYHswRb9OnwB3XHPNo

S4ZUhSULQk/YwbiEWQrWQRtkzCTJRh1zXnn6QsCZNju1MOrJyzGU2N+HPGUdYutdHo9Jr7Iw4

dpDKKVaCNQ8+q7/5kyB7BRmGH7IkvfnjsLdcsCHApZknerWpPY/8UzCgWoE6om0VuBoaDesLt

jBNlOWH+vUGHU9PBRzwoK0WzMx4vOZv5GoEYzCWy7MK6zo3nurTnmadrWsMQKVF93Ptm+hs7J

vu08thVQ25eJSuSHGU4p6OIEVhQZMP2apccDjJLYTi4OMYY/v0k8tTY9AIPA/cx6HKahCHoXg

s6MruAAU78xc3QTtYF0UiyTPBpdMVLhuA0pJ7joZIVRIIEXzhAbvKN1cpz9pPgL6qORV1hKwP

ppcfN+ejTtyMAxTokFddNYAyZGuM0ETCzDpkDsuEYPglA4Vx2l3eAFfep6EVWIyPx9QRuaYq5

wlHMBA0KubbmEfjgpT20QA9mxXDtQfkZ4nea02KQO2CZ8pz4SWFViN5KjCQNnPKJZl2cnyKX2

hfFKlkPu5/L3lma021LAsRl86LXTDORkJF4RDPUJ4rAZI1NryG8mukBXh57hkYsSzQ24GCM1O

2nA6sTwg6zk62emvBS+BdhZSWbN3rnBJT4pF4S22saBR8B0Okcc1eP/YpinUharIBXSoYcNRD

frFfuBO0DZgCF2+XOk7itnc4Zwdz4BVIwQBAwOQOHqpdN+uaIMtLL9mKht6QzNGC1ABod+EKb

0gfBpi+9P/UY3AHEDaSuUQEekbqPNSRDmZ7b1Ptka4oovHHaEFjM/7vr0RAW+N50QsltoB83L

cri4ajuTVYH8vfSDk63sJPBrdKCPpFOqK6vBf91vsuFowYtwlttrNQw0RFP1pOOMfbFY9B/Ca

H4zB4yW1boTWZj+sr9tNNYknZxyxGrR6B5XvPQj6auanEEHQdSzmeaZGxmjzbruMC4Jy8CjKS

y2S/BxxyHAdQq4jWparsXmYhekDM3UclIUdTBtPUFqa7e4pPldqd94GXOowdsxrpPCgDK+9tz

RPESnoUAGYkLglo3JsoEnL1Ksq42esk141KvA38Yt0/f4QQLq4z/D8nI+T3nANQsyj5LYsoS8

YOjTV/hqKSZZwJIYlPHbCM8trggZlg8DSq4yUJjirIBkYXRrtj2I1euB0JoVcQ3JJFh8GfGhZ

3XvjlU1cwpXMHW1zecI/bbfhw2NIwx2NwYW0i3qzTR/d5WFy0zGz2Xrm/p/5a9b1uJl5HaFIm

HJqS7laWQnemJiU9ZVgnMdPYxyPu1+f7/9QjJ/SSGZ6bOU0DDgtR56lz3FAnRiKXzrFlb/cCV

4nkq9UVE8c/ngsKOBTqQVHIGdiN51AYzg5/LLJz/PM4ssA1xTMHSXYLW2H7waZxYj+uQ7x6fR

FhcNOTUYV0CNNGZsPZ+thaGyTzI6AgJarkS19MkeQPV1YmergsPFhkgLoefJVFZYQVrePGQmS

yMLN8hW3Jpo/MSYhv7RRyPp5R2dsezTXCbUFmrEkg6rwGcXFIAzLG4lIHXwaS6pO1HQxHpA5A

JhQ8xqr4dy4vsAFcf6kk7PJEv4nTLXMnh3jaVHV6hzBPCo9YUPitmQPwjfZpnuug3eCsX3rHv

A6VD9tDgk1X+q26dJCQnJI4nPh5Hsr64RNvByQ4+KI0oLBrDzX4sw/SDflmeR4G7OWXX3IkjR

CvdbCjiAhjZFdGqDHZP0UbJDD0t/RdtarJeQSgfyhHGrKD+gXsgdL/lGcTj+B7hqNMN1vmgmg

1EcjEDMF+POA4tSB02jVT7B573gyS9qevU54oUuRjko+s6UDtkDjUSt6p0m68vYcXONZYWyl/

bQHNzObFcwpZ1wTSPLPONSZKwNP4NfwCO3ZQFbqj+dMIpZQa8aSoDeB8b/DdabWhJtprOvl5d

tVVb4sDO5j2637m2vWJ7ZuTz70dj3TLjvTXRsgS7ajoK5mrDuEvL8j0xw6z2pGJeSE+cAS+pe

zEE2oiWlKSylkOSwHzRSoVzXEZc9KfirAdOk+opW5J7Uc2Noe4o0NJx67ye5VC9EFhuO3djlf

I8PJ973S5EK8WTn09emI28g+9euUmpUUP0GagUVN4F14IWWaMO3FqqZObhbi32AmN0b+pm6VM

TWcKecWQ53cuvJrqwy4FYP1lYP7Bb+Slt7irDz04pmk5l9Urid5WoqmMGjMTXZ73szSOc1F6X

n+cB/rVRrSqNn3ahlak69fJ/mBsRRVj3DsDrR9RC46ZUKa2qpYD+riHfVTjr527w8l+5AaluU

C4fOT3ZMon6u4aAEdTG0jEF0agcAFVQUaaptwMR4C1+Bb8Qwj17k9eGhx2ARZDyPhXrxAdkjG

8Le2QnR+M93EVJwnr8tMwqNZ36XoZgdzfLX1hNOyNGnDKv0ZntlJaYIQQE9/TVkV5vU9eJkPF

UzWGiu7e+Mulkgnt1cIrtJyGo6wQoQnLO/x+ekPDYLqhtWoaLRychur3EkAh3cdBLfZWehjCf

dKn/ec1jrqFNnYI0M1amzaLbXlcOv9aT0U21j8QSWJWZQ2+eQ1sOuw1u3fhSYQNoDwKDO6DCv

9RN2oFYaJydNsr/ckZwbgE7e48lKsDTZNxlcQGZ1XM7b6cpccGrB6+pYKLb05qhrDxetMOK46

9l0nieMA9wk8nRkS4LJe7dn442zWx4oNnaV6OYMF39eFTVM4a7XEsIaC/gxLdJWQEDcdgjEyJ

aEMRMXoaG+xqXMNgx83J/dSFrX7HmpGFxS7G5OB87AcLuuTwin9q3UCyubV4REL+WD3cSIuUh

tzsps9cq91UjVhhx6VKbYf/Ebx/W7yIABPUeMWlO7GkJl+Brsc+LjhXN0CIXMBdw02UDK6flN

0vNpuK4NnZd1B11rJT+ap9e2+mxK0EDzszgneUYmp19ksPrgQ7pbHi9okEF0zpGfkI9ejyI/I

NR19vx/rpbm+8jeRF4Bcy5owkbWGxZN/4r8f91iW7E2oUWsGBCOjFFlE+CteO3BaAwjs1fS/+

lSiCG4Zpch5ZG/l6oex4BMHTH0BJtmCjkEWes8/vVoh4hExIKXZT1mCagj3IdHSKrX8j8eO5B

u0K5qj3nvMWdwXHOTbqvAvPgpT9Ir5aVGudgZGY0ZMmn7vTuVXtrSDKNRNmQ1e9DKL4Y/DVi4

3iUJRl6BiWA/1HJFswTEoHVr+xXIiIdG1fvDRZXsE3y4tRLCW2LBUDcSRVnySt7Cyw7/kChr9

/X/1kocVB0lIV7S6pwaWfAnyYyxfrdsYJTsVDfRWLXUwCyUxKE+M2LUrgp5gjmlTZHbL82GZ1

mTkYEQccO/QdkUwo7XWNh23jwi7UxQqWk/9t8M8+MJa0eC8iPfAnJzqbbGkcNQqOhDx2KQZ2o

XTB4junDS/t28ZlEJNRY4QX+Cs0ohFwLGI7Nysp6eC4LKgmStrssg3YVHpKm5fl6j7ytaZfEJ

/mdnm0VbYdRcVfahMONj8ygNei+PoS5zwdasdAFoT2FNoLnd1IQBM1TCBvpGbGzLB4vYNowdR

q+UL7qBtqxgnDCh5gC0y1+cVOMqBdXeicdorPHHBQkUPYz48A05bXTU1yYnguC+O2LODKUWVZ

ht5MgwT+6RI71H0fkieQJHSzwrjgzLemv4uxpFyQLIBy75H/Kw41SW+108TYN2dlgYTrxgbfe

Q+UzQe4QVeXDt4zhNaabn1ZSmHmTCO3q1G0j9Pmi73tkG0VjaboN5lhhe3zdixix5CR64891E

mYkOisAchgJAxS3FlpmYdHQwNgWHI4mLuaQ3MnzNcjbTzeRTveLzX1mZih1lzpyMqdey6cc07

OAzxWYilyyzmEQEsD3xOqie8o3hrzcyk4+5ykRllwTlOQAFhumAUIit6cmu5V2t4jIX0pyBZt

Pz6Wzbi5KnOjd1F3nTedtUEz3JuVTiglW5WzfaXweGdGA==

 

folgender Eintrag auf der Karte von morgen wurde verÃ€ndert:

 

Baumbeet (#non-profit)

BegrÃπnte Baumscheibe, Initiative der Stadt LÃ¶rrach in Kooperation mit der BÃπrgerschaft.

 

    Tags: baumbeet, gemeinschaftsgarten, grÃπn-in-der-stadt, stadtentwicklung, stadtgrÃπn

    Adresse: Pestalozzistr. 34, 79540 LÃ¶rrach, ,

    Webseite: https://www.loerrach.de/baumbeetpatenschaft

    Email-Adresse:

    Telefon: 07621 415-0

 

Eintrag anschauen oder bearbeiten:

https://kartevonmorgen.org/#/?entry=a48b8457b0f545998f395c393a69d1c0

 

Du kannst dein Abonnement des Kartenbereichs abbestellen,

indem du dich auf https://kartevonmorgen.org einloggst.

 

euphorische GrÃπÃƒe,

 

das Karte von morgen-Team

 

Weitere Hinweise und Tipps zur Nutzung, z.B. wie du interaktive Karten

per <iframe> auf deiner Webseite einbettest oder Papierkarten erstellst,

findest du hier: https://blog.vonmorgen.org

**Comment by wellemut** [comment]
Alle diese Formtierungs- und Spam- Probleme sollten seit der Umstellung auf sendinblue gelöst sein!
