### ISSUE TITLE
Rank search results by both total rating and scoring

### ISSUE THREAD

**Issue by uklotzde** [kartevonmorgen/openfairdb#186]
### Known limitation
~~When searching for entries the rating is not used for scoring the results. The rating is only considered in a post-processing step to sort the results.~~ The search result collector only considers the total rating of entries when building the (limited) result set. All entries that match the query are considered, independent how good they match the query.

### Consequences
~~If the number of available results exceeds the result limit then entries with a high rating might be missing.~~ Entries with a high rating are always shown, even if their are entries with a lower rating that score higher according to the search query. Refining the search by adding more search terms will not change the result, which might be unexpected.

### Proposed Solution

Combine the internal scoring of Tantivy with the entry rating to achieve a custom scoring of the search results. The rating should still be the primary criteria for the ranking, but the scoring should dynamically either boost or damp this value.

### See also
#183

**Comment by uklotzde** [comment]
I've added a TODO with a link to this issue: https://github.com/slowtec/openfairdb/pull/185/commits/7cec4d9c32338cf84e33f637698e349b2317f1fa

**Comment by uklotzde** [comment]
Currently the found entries are actually ranked by their total rating! Any entries that match the query are considered as candidates. When requesting 10 entries you always will get the 10 entries with the highest rating, as long as they match the query.

The only thing that is missing is considering the scoring related to the search query among those candidates, i.e. to boost entries that are better matching the query.

**Comment by fulmicoton** [comment]
Good news. Tantivy 0.10 will include a way to super simply and super efficiently rank by any function you can come up with to combine the default BM25 relevance score and any number of fast field you have (rating in your case).

**Comment by uklotzde** [comment]
@flosse @regenduft @ziedavid

**Comment by uklotzde** [comment]
Merged.

**Comment by fulmicoton** [comment]
@uklotzde Awesome!

**Comment by uklotzde** [comment]
@fulmicoton Thanks for your work, Paul! This feature is exactly what was missing here. I could adopt the example from the docs almost literally, really helpful. Migration from 0.9 to 0.10 was straight forward.
