### ISSUE TITLE
doc: adjust 404ing link to https://www.openfairdb.org/

### ISSUE THREAD

**Issue by fwolfst** [kartevonmorgen/openfairdb#189]
Two issues with the link to openfairdb (from githubs project description):

- https://www.openfairdb.org/ uses an Letsencrypt certificate for the domain api.ofdb.io
- https://www.openfairdb.org/ gives a 404 (remove the www and it will work).

Proposed solution: Fix 404 and certificate issue or adjust link in github project description.

**Comment by flosse** [comment]
Thanks for reporting!
