### ISSUE TITLE
Editing entries with reserved tags

### ISSUE THREAD

**Issue by uklotzde** [kartevonmorgen/openfairdb#203]
When creating or updating an entry it is verified that no reserved tags can be added by users or other organizations. But editing the tags of an existing entry when updating does not work as expected.

- The existing tags of an entry are not considered and all reserved tags can be removed by anyone without authorization.
- If the entry is edited by users that does not own any reserved tags they are even not allowed to provide the existing reserved tag again, otherwise their request would be rejected. They have no choice other than to remove all reserved tags.
- It is never possible to add 2 reserved tags from different organizations to an entry.

Desired behavior:
- Reserved tags can only added or removed by the authorized organization
- All existing reserved tags from any other organization are preserved and implicitly re-added if not already provided in the list of tags for the edited entry, i.e. if not authorized as an organization all reserved tags must be preserved when editing an event.
- Update requests that include some reserved tags that are already assigned to this entry should not be rejected

**Comment by uklotzde** [comment]
I have added a TODO comment with a link to this GitHub issue in the code

**Comment by wellemut** [comment]
I don't know if I understood it right.

Please make sure, that if an entry has a reserved hashtag, the whole event is not able to edit anymore. (Not only that users can not remove the reserved hashtag, but they also can not edit the whole event.

When an anonymous user creates a new event, he should not be able to choose a reserved hashtag.

**Comment by uklotzde** [comment]
This is not a trivial quick fix. The current implementation for entries is simply incomplete with the mentioned consequences.

For events all actions (create/update/delete) should work as expected.

**Comment by uklotzde** [comment]
Will be fixed by https://github.com/kartevonmorgen/openfairdb/pull/269

**Comment by uklotzde** [comment]
Fixed in v0.9.0
