### ISSUE TITLE
API GET /entries/recently-changed: missing tags

### ISSUE THREAD

**Issue by ubdu** [kartevonmorgen/openfairdb#209]
In some, but not all, cases the JSON-Result of GET /entries/recently-changed is not complete. 
Example:

> id | "1ec3e3ddea284fb1ac0f3fb666444a38"
> -- | --
> created | 1571942937
> version | 2
> title | "GSW Kundencenter Kamen"
> description | "Refill-Station\nÖffnugns…g \t08:00 bis 12:00 Uhr"
> lat | 51.5888416076027
> lng | 7.665069237195453
> street | "Poststraße 4"
> zip | "59174"
> city | "Kamen"
> country | null
> email | "service@gsw-kamen.de"
> telephone | "02307 978-2222 "
> homepage | "https://www.gsw-kamen.de/unternehmen/standorte#e1547"
> categories | []
> tags | []
> ratings | []
> license | "CC0-1.0"
> image_url | null
> image_link_url | null

"Categories" and "tags" are obviously missing, although the entry on the map has this data.

**Comment by uklotzde** [comment]
Confirmed. Categories and tags should be loaded. Seems to be a bug in the join&merge algorithm that works differently from the search query.
