### ISSUE TITLE
Script for Mass-Ratings to Branches of the same brand

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#215]
# Context
Since refill is using the map of tomorrow, we have a lot of bad companies like starbucks on our map, which users are annoyed of. We need to hide them somehow better, that they only appear, if nothing else is visible on the map.

# Idea
@uklotzde 
Is it possible to access the rating databasis from outside?
Could we find somebody like Michael from refill, who writs a script, that copies the same rating from one entry to all other from the same company?

**Comment by uklotzde** [comment]
No, the database is only accessible through the API. Direct access to the database neither (technically) supported nor desired.
