### ISSUE TITLE
complete openapi.yaml

### ISSUE THREAD

**Issue by flosse** [kartevonmorgen/openfairdb#22]
- https://openapis.org/specification
- http://swagger.io/

**Comment by wellemut** [comment]
@uklotzde 
Please update Swagger für Events.

I do not understand what means    "registration": "telephone"
What is saved there?
Please explain better, who can use the "Organizer" field and the "created_by" field which is relevant for https://github.com/kartevonmorgen/kartevonmorgen/issues/635

@regenduft what else was poorly or wrongly explained in swagger, when we repaired the event function?
