### ISSUE TITLE
Wrong dateTime is used when editing an event

### ISSUE THREAD

**Issue by naturzukunft** [kartevonmorgen/openfairdb#231]
If i create an event (in my case with the API) and after that open it for editing, the dateTime is: 1970-1-19

**Comment by uklotzde** [comment]
User-provided time stamps are specified in seconds as before:
https://github.com/kartevonmorgen/openfairdb/blob/master/openapi.yaml#L1015

Only system time stamps are recorded in milliseconds. But those are not intended to be used for business use cases.

Please provide an example request and the corresponding actual/expected response.

**Comment by naturzukunft** [comment]
@uklotzde open http://mobile.kartevonmorgen.org/#/?entry=467d5b2df545473f972f11b8631e3739 and edit the entry. >Then the time is wrong. Seems to be a ui bug. The entry above is an existing, it's not from me.

**Comment by uklotzde** [comment]
This is a UI bug, the timestamps are both correct (specified in UTC, interpreted as naive, local time at the event location).

**Comment by naturzukunft** [comment]
There seems to be a strict separation between ui and backend. I know that from big corporations. However, they are now working on this problem.

https://github.com/kartevonmorgen/kartevonmorgen/issues/645

**Comment by wellemut** [comment]
> 
> 
> There seems to be a strict separation between ui and backend. I know that from big corporations. However, they are now working on this problem.
> 
We are a huge cooperation!
-Never the less, as many issues are created by users, who do not know if it is a fronend or backend issue, we do not strictly seperate the issues. But thanks. I updated your new one.
