### ISSUE TITLE
Archive Events (Delete function)

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#234]
# Problem
Wrong, old, duplicates, useless Event-Entries can only be moved to the Atlantic, but not deleted. 
Sometimes it is need.

# Solution
Like we have it for entries, we need a backend interface to archive events. 
Do it the same way as for events.

**Comment by uklotzde** [comment]
TODO: Admin interface

**Comment by wellemut** [comment]
Actually Missing in Admin-Interface
- Possibility to click on an event or search an specific event
- Back-Button, after you selected an event, but you want to get back to the list.

But this has no importance right now!

**Comment by wellemut** [comment]
Actually Missing in Admin-Interface
- Possibility to click on an event or search an specific event
- Back-Button, after you selected an event, but you want to get back to the list.

But this has no importance right now!
