### ISSUE TITLE
csv export of Events (and extend it)

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#235]
# Problem
Regional- and Thematic Pilots need their events and places in other software, to create publication or use it to organize their networks. Now there is no way how to get out your events.

# Solution
Downloadfunction: Der Export von Events ist möglich + Administratoren können sowohl bei Events als auch bei Places die geschützten Felder (eMail + Tel.)  exportieren: 

- It is one download file for all types (events, places) of an area, the user has to filter it by himself afterwards if needed.
- The Mail and phone is via a new download link. Other link, where no mailadress is availiable, stays in place and usable for pilots, we can trust less.

**Comment by uklotzde** [comment]
v0.8.9 (to-be-released soon): Admins können alle Felder von Events exportieren (created_by + email + phone), jetzt auch ohne Token.

|Role|created_by|contact email/phone|
|---|---|---|
|Guest/User|:x:|:x:|
|Scout (without token)|:x:|:heavy_check_mark:|
|Scout (with token)|:heavy_check_mark: (owned events) / :x: (other events)|:heavy_check_mark:|
|Admin|:heavy_check_mark:|:heavy_check_mark:|

:x: = *exported fields are empty*

**Comment by uklotzde** [comment]
Die normale Suche liefert hingegen immer auch email/phone ohne Einschränkungen bzgl. der Rolle.

**Comment by wellemut** [comment]
Thank you very much. I just described this process on our blog: https://blog.vonmorgen.org/iframes/#download-der-karten-eintraege

**Comment by wellemut** [comment]
This Event-Export works grate.
(Next improvement would be, that I can connect Scouts in the Backend with a certain token, so that the user does not have to install the Rested-Adon in firefox to download their mailadresses.)

This function can now be transfered to entries too:  https://github.com/kartevonmorgen/kartevonmorgen/issues/656
