### ISSUE TITLE
New subscription fails "Mailadress already in use"

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#242]
# Problem
I tried to register to show how to subscribe to an area, but I failed. Error "Error while signing up. This email-address seems to already be in use."
Watch the end of this video: https://www.loom.com/share/0c3cd19aee7d402ea5e4aa5f7660f4d2

Seems that the connection to backend changed.
The last succesful proof was on the 21.1.20 while recording this video: https://youtu.be/FxYtvAw_psU

**Comment by uklotzde** [comment]
Cannot reproduce. All actions (subscribe, unsubscribe, update) on kartevonmorgen.org for a newly created account work without any issues.
