### ISSUE TITLE
Add opening hours for places

### ISSUE THREAD

**Issue by uklotzde** [kartevonmorgen/openfairdb#244]
- Store opening hours in a new text field
- Use OpenStreetMap format by convention:
   - https://wiki.openstreetmap.org/wiki/Key:opening_hours
   - https://github.com/opening-hours
   - Generator tool: https://projets.pavie.info/yohours/
   - Validation & evaluation tool: https://openingh.openstreetmap.de/evaluation_tool/
- The data will not be validated or normalized by ofdb in the first step
- Invalid data that does not match the OSM format might be deleted during future migrations

**Comment by wellemut** [comment]
Main Issue for this: https://github.com/kartevonmorgen/kartevonmorgen/issues/383

**Comment by uklotzde** [comment]
Deployed
