### ISSUE TITLE
recently-updated seems to be always empty

### ISSUE THREAD

**Issue by ghost** [kartevonmorgen/openfairdb#250]
Hi,

I can't get the recently-updated Endpoint to work. It always passes an empty result.
E.g. for sine : 1545403509 and until : 1568019754 there should be results.

The other endpoints give me entries with a creation date in between the timeframe mentioned.
easy reproducable on swagger.io.

Does anyone else experinence this kind of behavior?

**Comment by uklotzde** [comment]
until: 1568019754 = 2019-09-09T09:02:34+00:00

OpenAPI spec:
> ...the change history is restricted to the last 100 days.

**Comment by uklotzde** [comment]
https://kartevonmorgen.org/api/v0/entries/recently-changed?since=1545403509

Time stamp of the oldest/1000th entry: created = 1579711496

**Comment by ghost** [comment]
Ok,
Seems legit. I see your Example is working.
Thanks for the fast response.

**Comment by wellemut** [comment]
Hi @Leo172 
Nice to see you here working with openfairDB
My I ask, what you are working on?

Thanks a lot

**Comment by ghost** [comment]
Hey @wellemut,

I am working for a regional social network. We want to populate our map with additional points of interest from your sources of 'karte von morgen'.

Best Regards
