### ISSUE TITLE
Remove or Improve 3-similar-character-search

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#253]
# Problem
The Textsearch got updated in a way, that makes it quite randomly
It might be connected to this commit https://github.com/kartevonmorgen/openfairdb/commit/abca68f93544dae91cdd084d8eecb6781da7bac4

It makes it nearly impossible to find the right entry in some cases. Like if you are searching for the one "Gemeinschaftsbank" you only find Gemeinschaftsgärten... https://kartevonmorgen.org/#/?center=49.336,8.849&search=Gemeinschaftsbank

# Solutions
A. Eather remove it completly
B. Or sort search results in two categories
   1. Exact matches
   2. Similar entries

@uklotzde what would you prefer? What ideas do you have to improve it?

**Comment by wellemut** [comment]
@uklotzde 
Warum findet die Suche hier in Basel keine **Gemeinschaftsbank** https://kartevonmorgen.org/#/?center=47.547,7.586&zoom=15.00&categories=initiative&search=Gemeinschaftsbank

Obwohl es genau dort eine gibt: https://kartevonmorgen.org/#/?center=47.555,7.569&zoom=13.00&categories=initiative&search=%23bank ?

Das ist doch sehr komisch oder?

**Comment by wellemut** [comment]
Es wäre aber interessant, wenn die Suche bei "Museumsgarten"
https://kartevonmorgen.org/#/?center=49.481,8.431&zoom=13.00&search=Museumsgarten

auch "Hack-Museumsgarten" finden würde https://kartevonmorgen.org/#/?entry=c13479218e654bc184b98361dfc98982&zoom=13.00

**Comment by uklotzde** [comment]
Fixed

**Comment by wellemut** [comment]
Zack, 2 auf einen Steich!

vielen Dan dir, beides läuft jetzt ja perfekt.
