### ISSUE TITLE
csv import of entries and duplicate checker

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#254]
# Problem
- EWN needs to map around 3000 initiatives in NRW, which they have in their Databasis
- They can not ask them to map themselves, because they have around 20 other questions to aks, which we do not want/ need in our entry form, because most of the questions are to fast outdated or just not relevant for our users.

# Solutions
- import entries from a csv file, 

## checks for duplicates
Attributes:
A. **Distance**: If they closer than 10 m -> 100 duplicate; if larger than  500 m -> 0% duplicate
B. **Webseite**: If they have the same URL-basis or, 
C. Matching **Mailadress** or **phone-number** is a 100% duplicate. If they have the same Mailing-Adress-Domain which is not @gmail.com, @posteo.de or one of those big mailingsystems -> its a hint, like 80% duplicate...
C. **Title**: What percentage of words match? 

Give a list with five categories:
1. If all is true: its a duplicate
2. If three things match or B and C match: probably duplicate
3. If two facts match: could be duplicate
4. If B and C is true: similar
4. If none is true: no duplicate

In the List: 
- show both entries, the older one left, the newer one right
- under each entries give a button "Keep". (The otherone will merge away)
  - Keep the title, short description and Adress, Contactdetails of the entry which is to keep
  - merge all tags from the other to the one that stays
  - merge all PositivImpact ratings from to the one that stays. 
- Redirect the the URL of the lost one to the one that stays (on Kartevonmorgen.org), 
- mark the lost one in openfairdb.org as archived and give a link to the duplicate.

## Dependencies
- ~~Backend Duplicate checker: https://github.com/kartevonmorgen/openfairdb/issues/257~~ (done)
- Might be relevant for Fairsync too, possible synergies: https://git.fairkom.net/fairsync/events/issues/4

Similar: 
doublicates, dublicates https://github.com/kartevonmorgen/kartevonmorgen/issues/714

**Comment by mgnisia** [comment]
Hey guys :) 

here is Moritz vom [Einmal ohne, bitte](https://einmalohnebitte.de/). Helmut and I talked this week about possible forms how to work together. I also worked a little bit on the synchronisation with a simple python script to compare the entries of the karte von morgen with ours, as an example I took an area around Munich. 

Actually I used a quite similar approach: 

1. Took the Lat / Lon Data -> rounding to 6th decimal -> comparing those (identical to Criterion A)
2. Comparing the Title 
3. Comparing the Email Adresse

I will try your criterions as well and see how it works 👍

**Comment by wellemut** [comment]
Duplicate-Checker should not just clean the existing databasis but also be accesible for new imports: https://github.com/kartevonmorgen/openfairdb/issues/257

**Comment by flosse** [comment]
Here is the relevant code: https://github.com/kartevonmorgen/openfairdb/blob/master/src/adapters/csv.rs

**Comment by flosse** [comment]
And some duplicate checking code: https://github.com/kartevonmorgen/openfairdb/blob/master/src/core/usecases/find_duplicates.rs

**Comment by uklotzde** [comment]
Duplicate checker API implemented in #277: `POST /api/search/duplicates`

**Comment by wellemut** [comment]
This is the python import script form @paviro  https://cloud.freecommunication.org/index.php/s/f6bsQKWP3abosLP

@flosse do you need this script for import of the EWN-Data?
@paviro can you extend your script, to check of duplicates? ( You have seen, that i just sended it to a woman in Norway for an import)

Thanks to everybody!

**Comment by flosse** [comment]
## Draft of an algorithm

Pseudo Code:
```rust
/// Transform CSV into a suitable format
let result : Result<Vec<_>> = records
  .into_iter()
  .map(|record|  transform_record_to_ofdb_entry(record))
  .collect();

match result {
  Err(err) => {
     show_error_to_user(err);
  }
  Ok(entries) => {
     check_and_import(entries);
  }
}
```

```rust
/// Import with duplicate checking
for entry in entries {
   match is_duplicate(entry) {
      Some(id) => {
         match ask_user_what_to_do {
            Ignore => { /* do nothing */ }
            CreateAsNew => {
               import(entry)
            }
            Merge => { 
              let current_entry = get_newest_version(id);
              current_entry.contact = new_entry.contact; // overwrite
              current_entry.tags = merge(current_entry.tags, new_entry.tags);
              current_entry.description = current_entry.desc + "\n---\n" + new_entry.desc;
              current_entry.founded_on = new_entry.founded_on; // overwrite
              current_entry.custom_links = merge(current_entry.custom_links, new_entry.cutom_links);
              update(current_entry);
            }
         }
      }
      None => {
         import(entry)
      }
}  
```

```rust
pub fn transform_record_to_ofdb_entry(r: Vec<String>) -> Entry {
   let mut e = Entry::default();
   e.title = r[4];
   e.description = r[151];
   e.street = Some(r[5]);
   e.city = Some(r[6]);
   e.homepage = Some(r[10]);
   e.links = vec![
    Link { url: r[11], title: Some("Facebook".to_string()), description: None },
    Link { url: r[12], title: Some("Instagram".to_string()), description: None },
    Link { url: r[13], title: Some("Twitter".to_string()), description: None },
    Link { url: r[14], title: None, description: None },
   ];
   let mut tags = vec![];
   for in in 19...=151 {
     if !r[i].is_empty() {
       let tag_name = records[1][i];  // record 2 column i
       if !tag_name.starts_with("[") {
         tag.push(tag_name);
       }
     }
   }
}
```

**Comment by flosse** [comment]
**FYI:**
I started a simple CLI to import entries from JSON: https://github.com/kartevonmorgen/ofdb-cli

**Comment by flosse** [comment]
I think we can close this issue because `ofdb-cli` can handle the import now :)

**Comment by flosse** [comment]
I'm sorry, I was wrong ... `ofdb-cli`  can handle only JSON not CSV

**Comment by wellemut** [comment]
I just started documenting, how this function works and can be used: https://blog.vonmorgen.org/export-import/#import-von-daten
