### ISSUE TITLE
Backend not shown as logged in, when comming by link

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#260]
@uklotzde Can you explain this issue:

When I am clicking on the new  link "View history or archive this entry" at the button of an entry, (i.E. here: https://test.kartevonmorgen.org/#/?entry=193adf4ca4b44c33ad01502a7c11a2f5&zoom=14.00&left=show) I am comming to the backend-page of this entry. (in this case here: https://openfairdb.org/entries/193adf4ca4b44c33ad01502a7c11a2f5)
![InkedScreenshot_2020-05-09 Karte von morgen_LI](https://user-images.githubusercontent.com/15019030/81470683-5ace4b80-91ec-11ea-99ef-2bf97d555ba4.jpg)

But although I have been logged in to openfairdb.org the page is shown as if I am not logged in.
![grafik](https://user-images.githubusercontent.com/15019030/81470759-d5976680-91ec-11ea-96ad-4e152e80ef4d.png)
Even when I just click reload page, nothing is changed.

Only when I click in the URL-line and press enter. The page reloads and I am logged in.
![grafik](https://user-images.githubusercontent.com/15019030/81471302-6ae82a00-91f0-11ea-8607-7ff7a9744902.png)

Can you explain this? Does @navid-kalaei has to change something on the frontend or can you solve it in the backend?

Thank a lot.

**Comment by uklotzde** [comment]
Unfortunately the frontend and (admin) backend use two different sessions contexts. You have to login separately.

**Comment by wellemut** [comment]
@uklotzde 

> 
> 
> Unfortunately the frontend and (admin) backend use two different sessions contexts. You have to login separately.

This is clear! But even when I am logged in, and click on the link. The page is shown as if I would be logged out.

**Comment by uklotzde** [comment]
@flosse ???

**Comment by wellemut** [comment]
@uklotzde 
@flosse and me could not finde the problem today. But it is independet from the frontend. The same happens from whatever page you set the link: https://blog.vonmorgen.org/test/
