### ISSUE TITLE
Zusätzliche Felder in der API - search

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#272]
@uklotzde 
Die app-Entwickler von SimpliCITY aus Salzburg https://www.simplicity-project.eu/ haben folgende Frage an dich. Was hälst du davon?

Wir holen aktuell alle 24 Stunden die Einträge aus Salzburg über die folgende API ab:
→ https://api.ofdb.io/v0/search?bbox=47.75109722475341,12.864646911621094,47.84484664362789,13.227367401123049&limit=500

Leider sind in dieser API die Felder "hompeage", "email" & "image_url" der Einträge nicht enthalten.
Da wir Interesse an diesen Feldern haben holen wir diese separat für alle Einträge über die folgende API ab:
→ https://api.ofdb.io/v0//entries/:entry_id

Wenn es OK wäre wenn diese Felder ("homepage", "email" & "image_url") zusätzlich direkt über die "search" API ausgeliefert werden dürfen,
dann können wir die 24 Stündlichen kurzen Belastungen eurer API ein klein wenig reduzieren.
Oder wir könnten uns erlauben das Intervall eventuell sogar stündlich durchzuführen.

**Comment by wellemut** [comment]
Aus Spamschutz-Gründen bin ich persönlich unsicher, ob wirklich gleich alle Mailadressen mitgenommen werden sollten. Das könnte dann ja jeder gleich haben. Vielmehr müssen wir die Mailadressen eigentlich mit Token irgendwann noch besser schützen. Aber Homepage, Telefonnummer und Immage-URL sollten eigentlich gerne gleich mitkommen dürfen.

**Comment by uklotzde** [comment]
Adding individual fields one by one is tedious. In this case we need to discuss how to customize the results, i.e. how to switch between a *brief* and the *full* representation on demand -> new query parameter.

The full representation will require additional database queries, but at least it won't incur additional client/server round trips like the current workaround does.

**Comment by uklotzde** [comment]
The complete entries for all search results can be retrieved with a single, subsequent API request by providing a list of comma-separated ids:

```
GET https://api.ofdb.io/v0//entries/id1,id2,id3
```

We are aware that this is not a REST-like method for historical reasons. But it does the job.

It's not worth to extend the API for saving only a single client/server round trip.

**Comment by cw789** [comment]
Hey, I must agree to the points made by @uklotzde.
I just tested to use `GET https://api.ofdb.io/v0/entries/id1,id2,id3` and it's working.

I didn't use it in the first place as we query 70 entries (growing) & so I thought some time the URL length could get a problem.
Currently it's 2341 chars long. I hope we won't hit any implementation limit by your server or proxy.

But anyway - for now this is the better option.
If we will hit a limit - batching the request with this API would still be the better option.

So, thanks. Issue can be closed.

**Comment by uklotzde** [comment]
@cw789 I remember that the Kvm frontend experienced issues with maximum URL length. Since the length of each id is fixed you could split the request into batches with a maximum number of ids per request just to be safe.
