### ISSUE TITLE
use serde

### ISSUE THREAD

**Issue by flosse** [kartevonmorgen/openfairdb#28]

**Comment by flosse** [comment]
...waiting for `rusted_cypher` `v1.0` that supports `serde` `v0.8`

**Comment by flosse** [comment]
serde `v0.9.0` just [released](https://github.com/serde-rs/serde/releases/tag/v0.9.0), so hopefully [rusted_cypher will take that!?](https://github.com/livioribeiro/rusted-cypher/issues/12)

**Comment by livioribeiro** [comment]
Just published `rusted_cypher` `v1.0.0-rc2` using `serde` `v0.9`. There are a couple breaking changes (despite being a rc release, sorry) caused by changes in `serde_json`.

**Comment by flosse** [comment]
cool, thanks!
Don't worry about the breaking changes :)

**Comment by flosse** [comment]
@livioribeiro it seems to work :) Thank you!
