### ISSUE TITLE
Allow to compile the whole project on stable rust

### ISSUE THREAD

**Issue by flosse** [kartevonmorgen/openfairdb#293]
There are currently two frameworks that require Rust nightly:
- [x] [maud](https://maud.lambda.xyz/) (corresponding [issue](https://github.com/lambda-fairy/maud/issues/17))
- [ ] [Rocket](https://rocket.rs/) (#399 )

**Comment by lambda-fairy** [comment]
FYI, lambda-fairy/maud#17 is now closed :slightly_smiling_face:

**Comment by flosse** [comment]
> FYI, [lambda-fairy/maud#17](https://github.com/lambda-fairy/maud/issues/17) is now closed slightly_smiling_face

awesome! :+1:

**Comment by flosse** [comment]
#399
