### ISSUE TITLE
[Wireframe] Moderationscenter: Interface for duplicate checking

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#301]
# Problem
- While importing new entries, we have to make sure, they are no duplicates of existing ones.
- Movements with 50 and more entries like #Weltladen want to know, if they have duplicates on our map. Manual checking like browsing the map takes too much time.

# Solution
As we have all the logic about duplicate checking in the ofDB alreay, we just need an interface (similar to the clearance center https://openfairdb.org/clearance/ Login with test-token 24vGG9gyYuVanmjJBJCRzZ51Qt5GBYGxkEGu1BxNQhQBgQ7) where duplicates can be checkt. 
![grafik](https://user-images.githubusercontent.com/15019030/128906951-1916eeb2-c346-438f-b52e-657774575ae9.png)

Here is a possible usterstory:

**1. While import**
- User has imported a feed (from OpenstreetMap, Wechange.de or any other Database, that provides the data in LoA-format.)
- All entries are listed by their possibility of beeing a duplicate. The most possible duplicates at the top. At the bottom there are those entries, which surely are no duplicates and can be imported.
- User clicks for each duplicate "merge" if it is a duplicate or "create new" if it is no duplicate and should be imported.
  - With a button "compare entries on the map" the user can open a map-view with two colums (or more?) to compare possible duplicates and merge them visually on the map: https://github.com/kartevonmorgen/kartevonmorgen/issues/835
- A definition, how to define a duplicate is given here: https://github.com/kartevonmorgen/openfairdb/issues/254
- When the user is done, he can click "proceed import" and all new entries are created and duplicates will be merged.

**2. Search for duplicates in kvm**
- Searchfield: User enters a searchterm like 'Weltladen' and a bbox which he wants to get checked for duplicates, and presses <search duplicates>
- The function will search (in the given bbox) for all corresponding items and send their IDs to the duplicate checker
- The Users sees a list grouped by duplicates. So the list has sections where two or more entries are shown, that might be duplicates. 

As anonymous users can not archives entries, this function is only for Pilots (logged in)

---
Alternative Issue for Frontend-Implementation: https://github.com/kartevonmorgen/kartevonmorgen/issues/835

Prerequisits
- The script is based on a levinstin duplicate checker which is build by Fredy
- Import form OSM: https://github.com/kartevonmorgen/kartevonmorgen/issues/13

**Comment by qknight** [comment]
@wellemut hi

**Comment by wellemut** [comment]
Waiting for the Mapper format: https://github.com/kartevonmorgen/FairSync/issues/17

**Comment by wellemut** [comment]
Import-Center and Moderation Center are somehow linked and designed together by @qknight https://github.com/kartevonmorgen/FairSync/issues/17#issuecomment-2405504752

**Comment by wellemut** [comment]
This desicion was done to a different Interface for duplcate moderation: https://github.com/kartevonmorgen/FairSync/issues/17#issuecomment-2462569849

Thank you @qknight
