### ISSUE TITLE
Contact Name field for places

### ISSUE THREAD

**Issue by navid-kalaei** [kartevonmorgen/openfairdb#312]
## Problem:
The organizer should be known for places.
But when I enter an Name, it is not stored: https://www.test.kartevonmorgen.org/#/?entry=719355c314e14a0280310b790a61dcad&center=52.456,13.571&zoom=15.00&search=%23gemeinschaftsgarten

## Proposal:
Considering a field for places to store/restore organizer for places like we already have for events

## Related issues:
Extend Entry Form for Contact Person kartevonmorgen/kartevonmorgen[#705](https://github.com/kartevonmorgen/kartevonmorgen/issues/705)
New fields for POIs that represent organizations kartevonmorgen/openfairdb[#279](https://github.com/kartevonmorgen/openfairdb/issues/279)

**Comment by uklotzde** [comment]
https://github.com/kartevonmorgen/openfairdb/blob/6ca4b13481408fa7b962bad312d244036a49bb33/openapi.yaml#L808

The request sends an `organizer` instead of `contact_name` as documented. Only events have an organizer, this term doesn't fit for places, because you can't *organize* a place.

**Comment by uklotzde** [comment]
Not a bug.

**Comment by wellemut** [comment]
Thanks Uwe, so it is well documented.
For me it does not matter if organizer or contact_name but I think it makes sense to use the same term.

In https://schema.org/Organization they only use employee and organizer. So I think, organizer would be nice for both...

**Comment by navid-kalaei** [comment]
Many thanks Uwe. I fixed [the issue on the front end](https://github.com/kartevonmorgen/kartevonmorgen/issues/705) based on Uwe's guideline and it's perfectly functional. if there is anything that needs to be considered please let me know :rose:
