### ISSUE TITLE
Do Autocomplete for hashtags in the backend? -> WASM-Module

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#321]
## Problem
Loading and suggesting tags while searching is killing my smartphone. It gets too slow.
The Frontend does the alphabetically sorting and caches all 10.000 tags for this : https://github.com/kartevonmorgen/kartevonmorgen/issues/495 this should be used to the backend

Loading all tags, although it starts with the most used ones, still needs 5 requests: https://github.com/kartevonmorgen/openfairdb/issues/255

## Solution
- Create an API that suggests X most likely tags while typing (X could be 10)
- Delay the API call for Y ms of inactivity (X could be half a second)

**Comment by flosse** [comment]
~~What about using the search responses from the `/search` endpoint?
We could extract all tags out of these instantly.~~

**Comment by flosse** [comment]
What about extending `/entries/most-popular-tags` with a query parameter?
So e.g. `/entries/most-popular-tags?min_count=10&limit=5&q=slow` would return the 5 most popular tags that contain `slow` and have a min count of 10.

@uklotzde ?

**Comment by wellemut** [comment]
Thats great. 
The default min_count would be 1, because tags that are not used, we do not want to suggest. But all used tags might be intresting, not only thos used 10 times.
and if there are 5 tags, used more the 10 times, it anyway does not show those used less.
How much does the number of "limit" affect the speed? 
I think a limit of 10 would be better than five. Google also suggests 10.

**Comment by wellemut** [comment]
We do not autocomplete tags from the beackend, but @flosse developed a Rust-Function which can be included in the frontend:
https://github.com/kartevonmorgen/kartevonmorgen/pull/806

Function just needs the number of wished results and the searchstring:
https://github.com/kartevonmorgen/kartevonmorgen/blob/kern/kern/src/lib.rs

@flosse please describe how to include your function!

**Comment by flosse** [comment]
In addition https://github.com/kartevonmorgen/openfairdb/pull/330 should speedup the overall tag completion :)

**Comment by flosse** [comment]
> @flosse please describe how to include your function!

There is nothing to do... it's already included in the PR ;-)

**Comment by wellemut** [comment]
@navid-kalaei  is still thinking, if the function should be implemented in backend, thats why I am opening it agian.
it's not possible to put the pressure of suggestions on recommendations on the clients shoulder. event for the tags we are storing a huge number of tokens on the client's device, what a mess! let's have the logic of the recommendations on server and I will integrate the feature with the fronend with pleasure. if it's not feasible for slowtec please let me know to find an alternative.

**Comment by flosse** [comment]
@navid-kalaei Integrating the WASM module is really easy, just extend the HTML with this:

```html
    <script type="module">
      import init, { Core } from '/kvm_core.js';
      if (init && Core) {
        init().then(() => {
          window.ofdb = { kvm_core: new Core() };
        });
      }
    </script>
```
Don't forget to deploy the two corresponding files: `kvm_core.js` an `kvm_core_bg.wasm`.
If you don't know how to build the WASM module I could send you the files.

To fetch popular tags, you can do it like this:
```js
const MAX = 5; // amount of suggestions
core.popular_tags(MAX, search_term).then(tags => { tags.forEach(t => { console.log(t); });});
```

**Comment by wellemut** [comment]
As we use the WASM Module in the frontend, I close this issue.
A new API is availiable: https://github.com/kartevonmorgen/openfairdb/issues/344
