### ISSUE TITLE
Sending ID="null" could be an error

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#342]
3. base on the filed of NewEntryWithLicense the field id should not be present in the request,.

But that is an error in the documentation! It's in the conflict that if I don't provide a field of id with value of null the record would not be created, 

Solution: 
We should change the schemas in the backend to drop the Id completley as it is already in the header...

**Comment by wellemut** [comment]
Similar issue: Update Swagger Post example: id:"null" mandatory while creation #339

**Comment by magdaddy** [comment]
Yes, the slight "unsynchronicity" between Swagger spec and the backend _is_ annoying, I ran into that myself a couple of times (I'm also still new to ofdb), and I would like to see it fixed.

I have a couple of ideas for automatically testing spec compliance, but they are on the backburner right now.

So, in the meantime, unfortunately, a little creativity and problem solving skills are sometimes required by the API user... ;-) #340 #341 #339

**Comment by wellemut** [comment]
@navid-kalaei 
Could you please try to provide a better description?

As described in swagger, you should not include the ID when updating.
![grafik](https://user-images.githubusercontent.com/15019030/125598277-f73aacc4-0e43-463c-8c2d-156e41fe0273.png)


Please, reopen, if its still a problem.
