### ISSUE TITLE
Mailservice stopped working

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#343]
# Problem
No mails are send anymore
- not for changes on the map (Subscribers)
- not for registration-confirmations mails or passwort resets

# Solution
- Option A: Find Error in the backend service
- Option B: Get new service running: https://github.com/kartevonmorgen/openfairdb/issues/194

**Comment by wellemut** [comment]
@flosse 
Thank you very much for bringin it up again. Since Mi., 21.04.21, 21:50 Mailnotifications are flowing again!

Could you document how you solved it or link the merge request? 
- Is it the old Mailservice on the client?
- Or does it run on a new professional service?

**Comment by flosse** [comment]
it's working again, the mail server changed some things.
