### ISSUE TITLE
API to get most-popular-tags

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#344]
Great, that we have the new tag-Suggestions API now
![grafik](https://user-images.githubusercontent.com/15019030/115621444-cffc3900-a2f6-11eb-937e-0135631b2af7.png)

But when I search for #klimanetzwerk it does not suggest it
![grafik](https://user-images.githubusercontent.com/15019030/115621647-1a7db580-a2f7-11eb-8ba5-3ff148e16e5b.png)

On an Kartevonmorgen-Tab which I loaded this morning, I get the suggestions
![grafik](https://user-images.githubusercontent.com/15019030/115621749-3da86500-a2f7-11eb-94bc-3342500d61fc.png)

I will test it a little bit, but it seams, that with the new backend, the new "GET ​/entries​/most-popular-tags Get most popular tags for entries" might not deliver less used tags.

**Comment by wellemut** [comment]
@navid-kalaei This API solves the our Hashtag-Suggest Problem.
But still the best way is to use it together with the WASM Modul: https://github.com/kartevonmorgen/openfairdb/issues/321

**Comment by wellemut** [comment]
Großartig, @flosse, hast du heute nochmal was am Server und der API geschraubt?
Mir scheint, als ob mir alle Hashtags wieder vorgeschlagen werden. Keine Ahnung, woran das liegen könnte...

**Comment by wellemut** [comment]
scheinbar zu früh gefreut
![grafik](https://user-images.githubusercontent.com/15019030/115973544-17cccb80-a556-11eb-8e26-189a8dcab3ac.png)
regionalgruppe ist eigentlich ein sehr häufiger tag

![grafik](https://user-images.githubusercontent.com/15019030/115973569-4ea2e180-a556-11eb-89d7-bbf4a5880838.png)
Stattdessen wird aber nur #regionalgruppelernkulturzeit vorgeschlagen, was recht selten ist.

**Comment by wellemut** [comment]
Also the Hashtag-Preview does not work in the Glossary of Change: https://glossardeswandels.de/tagcloud_kvm.php?mincount=20
![grafik](https://user-images.githubusercontent.com/15019030/116100907-a9028600-a6ad-11eb-8e00-0d482831b15a.png)

**Comment by flosse** [comment]
Reloading the cache with https://api.ofdb.io/v0/entries/most-popular-tags?max_cache_age=0 "solves" the problem for now
but in the long term we should fix this cache initialization bug!

**Comment by flosse** [comment]
Here we are...

https://github.com/kartevonmorgen/openfairdb/blob/f3c1bf8cf06007981f410f6e0c87ca32c84329b7/src/ports/web/api/entries.rs#L155-L161

https://github.com/kartevonmorgen/openfairdb/blob/f3c1bf8cf06007981f410f6e0c87ca32c84329b7/src/ports/web/popular_tags_cache.rs#L74-L78

This overrides the cache with the results of the request with `params` `pagination` :-\

**Comment by flosse** [comment]
should be fixed in `v0.10.2` :)
