### ISSUE TITLE
Serve swagger-ui

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#345]
Hi @flosse 
How complicated is it to set up an onw swagger instance like this? https://wechange.de/swagger/
It would make it esier for me to share our API, if i would just have one link...

see example: https://app.swaggerhub.com/apis/Kartevonmorgen/open-fair_db_api/

**Comment by uklotzde** [comment]
https://swagger.io/docs/open-source-tools/swagger-ui/usage/installation/

**Comment by wellemut** [comment]
I can import the ofdb yaml https://app.swaggerhub.com/apis/Kartevonmorgen/openfairdb/ but its not really auto-updating

I can manually import every new version: https://support.smartbear.com/swaggerhub/docs/apis/importing-api.html

**Comment by flosse** [comment]
The easiest solution would be to include the content of [swagger-ui/dist](https://github.com/swagger-api/swagger-ui/tree/master/dist) in the binary.
And within the `index.html` the configuration would point to the `openapi.yaml`.

**Comment by wellemut** [comment]
This system is very nice and helps very much https://app.swaggerhub.com/apis/Kartevonmorgen/openfairdb/

It still requires manual updating form my side, but thats feasible. 
I close this issue.
