### ISSUE TITLE
csv tag download

### ISSUE THREAD

**Issue by flosse** [kartevonmorgen/openfairdb#35]
The server should return list of tags with both the tag's name and the usage/reference count. Unused or orphaned tags will return a usage count of 0.

Optionally the maximum number of returned tags should be limited.

The results should be filtered by
- Usage count ascending
- Usage count descending (default)
- Lexicographically ascending
- Lexicographically descending

**Comment by elbotho** [comment]
could be done via a backend, e.g.
https://vm-backend.netlify.com/#/tags

**Comment by uklotzde** [comment]
The server should return list of tags with both the tag's name and the usage/reference count. Unused or orphaned tags will return a usage count of 0.

Optionally the maximum number of returned tags should be limited.

The results should be filtered by
- Usage count ascending
- Usage count descending (default)
- Lexicographically ascending
- Lexicographically descending

**Comment by wellemut** [comment]
Its done and documented in Swagger, how you download tags
