### ISSUE TITLE
csv tag upload

### ISSUE THREAD

**Issue by flosse** [kartevonmorgen/openfairdb#36]
parse, validate, merge

**Comment by uklotzde** [comment]
This is a very special use case and should only be implemented if the batch upload of tags is really needed. The more common use case to download all tags is covered by #35.

**Comment by wellemut** [comment]
The other usecase, to build hirachies, similariteis, siblings, parrents and child-relations is better documented in https://github.com/kartevonmorgen/kartevonmorgen/issues/598

and in https://github.com/kartevonmorgen/kartevonmorgen/issues/396
