### ISSUE TITLE
Documentation error: The required payload type is leading `/search/duplicates`

### ISSUE THREAD

**Issue by navid-kalaei** [kartevonmorgen/openfairdb#363]
## Introduction
The participant Krill from team Russia has spent hours trying to find the right payload for `/search/duplicates` and on every try he got error 422

## Problem
The documentation has specified the payload MUST have type NewEntry, which is not the actual type it accepts

## Solution
After many trial&errors the following scheme worked
```javascript

{
"id": null,
"categories": [
"2cd00bebec0c48ba9db761da48678134"
],
"title": "test",
"description": "test test test",
"tags": [],
"city": "municipality",
"zip": "57030",
"country": "Italy",
"state": "Tuscany",
"street": "37",
"lat": 42.750541777589376,
"lng": 10.152115243848346,
"contact": null,
"telephone": "+98 933 649 8639",
"email": "maxkalaei@gmail.com",
"homepage": null,
"opening_hours": null,
"image_url": null,
"image_link_url": null,
"license": "CC0-1.0",
"version": 1,
"links": []
}
```

**Comment by uklotzde** [comment]
Strange. According to the code the method accepts a `NewEntry` as documented in the OpenAPI schema.

Unfortunately there are no API tests that actually verify this behavior.

**Comment by uklotzde** [comment]
v0.10.4 now returns details of client-side API errors as a JSON body instead of only returning a HTML page.

**Comment by uklotzde** [comment]
The documentation is slightly wrong. You need to provide a `NewEntryWithLicense` with a `license` fields which doesn't really make any sense for this use case :see_no_evil:

**Comment by uklotzde** [comment]
Mandatory fields:
- title
- description
- lat
- lng
- license

**Comment by uklotzde** [comment]
c1423e499bd314276fd684a76346d0fb1846ce53

**Comment by uklotzde** [comment]
More mandatory fields are not documented:
- tags
- categories
- ~~links~~ (edit: custom links were always optional)

Minimum payload (v0.10.4):

```json
{
"title": "test",
"description": "test test test",
"lat": 42.750541777589376,
"lng": 10.152115243848346,
"license": "",
"tags": [],
"categories": []
}
```

**Comment by uklotzde** [comment]
ba6d778daea69f853cc5f2fa9ffb2efb6ae52c30

I will close this issue as resolved after fixing the docs. For the future the /search/duplicates API needs to be improved to not require passing unused fields!

**Comment by uklotzde** [comment]
#368
