### ISSUE TITLE
Show events as long as they are running: Add enddate to API

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#364]
# Problem
Festivals, Conferences and longer events are hidde after they have started, even if they are still running.

# Solution
The Frontend needs to be able filter by the Ending date (not only by the startdate)
If the users wants to see all events that are currently running the frontend could call
`show all events where "End-Date > NOW"`

That would esily solve the problem. Than the frontend-guy has to think a little bit more, but just with the start-date, he is unable to handle this probably

**Comment by uklotzde** [comment]
Add filter parameters `end_min` and `end_max` in addition to `start_min` and `start_max` to the API.
