### ISSUE TITLE
Implement Yandex.ru Geocoder additionally to to OSM-Nominatim

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#369]
## Problem
Our Russian partners will not be happy with our Geocoder in the frontend, because the open streetmap hardly finds any adress. OSM is really bad in Russia.

For the ofdb-cli it is the same. I can not find any of the adresses, I want to import. 

## Solution
Yandex.ru offers a free (for up do 25.000 requests per day) geocoder https://yandex.com/dev/maps/geocoder/

We should integrate their geocoder, in case OSM-nominatim does not return any results, as a fall back solution. So we basically would be in use of two geocoder at the same time.
(We somehow have to know, if Yandex was in use for a certain entry, because officially we would have to show credits to them on the map, but in this case, rather on the profile page of the geocoded entry.)

### Test adresses:
121609, г. Москва, Рублевское шоссе, 28
Смоленская обл, пгт Кардымово, Октябрьский пер, д 1, кв 1 

### Geocoding with Yandex:
— Requests to the Geocoder HTTP API. https://yandex.com/dev/maps/geocoder/doc/desc/concepts/about.html
— Calling the geocode() function. : https://yandex.com/dev/maps/jsapi/doc/2.1/ref/reference/geocode.html

**Comment by wellemut** [comment]
@navid-kalaei I guess the Russians soon will complain, that they can not find any address. Then you just could replace the geocoder in their frontend by Yandex...

**Comment by wellemut** [comment]
If Yandex is too complicated, we can try google: https://developers.google.com/maps/documentation/geocoding/overview

**Comment by wellemut** [comment]
Hä, did you just solve this @flosse ?

**Comment by flosse** [comment]
no but we have tooo many open issues so we can re-open this issue again if there is someone who wants to solve this or if there is a funding.

**Comment by flosse** [comment]
... see also #477
