### ISSUE TITLE
Offer Ical-Export for any filtered view

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#370]
## Problem
We can already import Events via the Wordpress-Plugin. But many organisations and private people want to integrate a selection of events within a certain area, timeframe and topic (selections of tags)  in their private or organisational calender. Either they can not, or they don't want to use our list- or mapview so they can not use the collectivly collected events in their calendars.
Lastenheft zur Bedarfsanalyse: https://wechange.de/project/gemeinsamer-kalender/document/bedarfsanalyse/ Es braucht nur ein Austausch-System, mit dem Termine importiert und exportiert werden können!)

### Functionality (Backend)
- Offer and Ical Feed
- But you need to be able to filter it the same way as you can filter the map. so it basically needs to contain all atributes like we have in the URL. The Ical feed needs to be filterable for 
  - bbox
  - tags 
  - timerange
  - Nice to have: Orgtag, free search
So the Ical-feed need to offer the full range of the ofDB-Event API.
Of course, the ical should only deliver events with start and ending date.

### Userstory (Frontend)
- The user goes to the map and searches the area he is intrested and filters for the tags he wants.
- The Ical-Feed will be offered in an additional Button at the botton right corner where you get the URL, and HTML-Code
  - The feed will probably look like the normal url, just with .ics at the end: https://kartevonmorgen.org/#/?center=48.010,7.859&zoom=11.00&categories=event&search=%23klimafit.ics

**Comment by flosse** [comment]
FYI: https://github.com/hoodie/icalendar-rs

**Comment by wellemut** [comment]
> FYI: https://github.com/hoodie/icalendar-rs

That looks great @flosse ! Would that help us building the ical Export?
We just had a call Today with Ulm and the question is, how fast could we get this done?

**Comment by wellemut** [comment]
Wir werden den Ical Export direkt aus der ofDB umsetzen @uklotzde. Markus wird dir dazu in den nächsten Tagen mehr sagen. 
Wir hoffen, die Bibliothek macht es uns leicht.

**Comment by wellemut** [comment]
@flosse vielen Dank für die Implementierung inkl. Dokumentation in https://app.swaggerhub.com/apis/Kartevonmorgen/openfairdb/0.12.2#/Export/get_export_events_ical wie das ICAL-Feature nun genutzt werden kann.

Ein Beispiel für alle Termine aus Deutschland
http://openfairdb.org/api/v0/export/events.ical?bbox=47.49,0.79,54.63,18.30
