### ISSUE TITLE
Rest API?

### ISSUE THREAD

**Issue by samuk** [kartevonmorgen/openfairdb#380]
Is there a simple API anywhere I can query?

My use case is to get this data https://kartevonmorgen.org/#/?zoom=6.00&search=%23transition&dropdowns=kvm overlay some pins on [www.transitioninitiative.org](url) map and send any clicks off to the original kartevonmorgen source.

https://api.ofdb.io/v0/ this link gives a 404 error for me. Has the service moved?

**Comment by samuk** [comment]
bump? Is there a rest API for Kartevonmorgen please?

**Comment by uklotzde** [comment]
Inspecting the network requests on kartevonmorgen.org will reveal the API endpoint: https://kartevonmorgen.org/api/v0

**Comment by uklotzde** [comment]
...but https://api.ofdb.io/v0/ also works when submitting request URLs according to the API docs. Otherwise you will get a 404 error as expected.

**Comment by uklotzde** [comment]
GET https://api.ofdb.io/v0/server/version
GET https://kartevonmorgen.org/api/v0/server/version
