### ISSUE TITLE
add date & short description fileds

### ISSUE THREAD

**Issue by regenduft** [kartevonmorgen/openfairdb#5]
date: https://github.com/flosse/kartevonmorgen/issues/22

short description: https://github.com/flosse/kartevonmorgen/issues/17

**Comment by flosse** [comment]
There won't be a short description, see https://github.com/flosse/kartevonmorgen/issues/17#issuecomment-174441121.

**Comment by flosse** [comment]
There also won't be a date field because events will be handled separately from entries.
