### ISSUE TITLE
Please update README.md

### ISSUE THREAD

**Issue by ourconomy** [kartevonmorgen/openfairdb#51]
Please update lines in
## Installing Rust and Cargo
as follows
```
     sudo apt-get install curl libssl-dev gcc
     curl https://sh.rustup.rs -sSf | sh
     rustup install nightly
     rustup default nightly
```
(Yes, gcc! It was missing in my fresh installation. And, you mention to use Rust nightly, but users could need the 2 extra lines for convenience.)

Then, to add Cargo to $PATH, please, log out and log back in. (Not very elegant, I know)

Thanks,
Oli

**Comment by flosse** [comment]
> Please update lines [...]

this is done, isn't it?

> Then, to add Cargo to $PATH, please, log out and log back in. (Not very elegant, I know)

This is done automatically by rustup as far as I know.
Feel free to reopen!
