### ISSUE TITLE
My suggestions on data structure

### ISSUE THREAD

**Issue by ourconomy** [kartevonmorgen/openfairdb#53]
Hi Markus,
The first part of my ideas on the records for a shop and product database are available!  

Please have a look at https://github.com/ourconomy/MarketCommons/ and let me know when I can help with additional information or comments.  

Cheers,   
Oliver

**Comment by ourconomy** [comment]
Hi all,
have you had a chance to look into my suggestions for a data structure?

Especially: Are you interested in adding products and services to Kartevonmorgen?

**Comment by flosse** [comment]
> Especially: Are you interested in adding products and services to Kartevonmorgen?

Well it's not a matter of interest it's a matter of capacity ;-)

**Comment by ourconomy** [comment]
I will focus on adding products to ofdb once the new setup is running on
my test system.

Products in KVM need a certain level of maturity: When products are
linked to places where you get them they are a valuable addition.
Otherwise they are difficult to integrate into the map or the search
area.
