### ISSUE TITLE
build for server fails

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#63]
`cargo build ` works but `cargo build --release --target x86_64-unknown-linux-musl` fails
this happened after pulling a7fc39730534382cf32ae454533ae40217ae3fb3 which changed rustc-version to `rustc 1.20.0-nightly (9b85e1cfa 2017-07-07)`

```
$ cargo build --release --target x86_64-unknown-linux-musl
   Compiling ascii_utils v0.9.3
   Compiling libc v0.2.26
   Compiling term v0.4.6
   Compiling smallvec v0.4.1
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed

error: aborting due to previous error(s)

error: Could not compile `ascii_utils`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed

error: aborting due to previous error(s)

error: Could not compile `term`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by david-ziegler** [comment]
`rustc --version`: rustc 1.20.0-nightly (696412de7 2017-07-06)

**Comment by flosse** [comment]
I guess this is outdated. Feel free to reopen the issue :)

**Comment by ourconomy** [comment]
connection to database and filling it now works for me.

Thank you!!

Am 2017-12-09 01:14, schrieb Markus Kohlhase:
> I guess this is outdated. Feel free to reopen the issue :)
