### ISSUE TITLE
Proposal of specification for valuations' data structure

### ISSUE THREAD

**Issue by ourconomy** [kartevonmorgen/openfairdb#64]
Hey guys,
I completed my draft of the second part of my proposal for a database structure: Valuations!
Please see the files
MarketCommons_Database_v0.067.ods
MarketCommons_FS_-_Valuation_part2ver0.030.pdf
in
https://github.com/ourconomy/MarketCommons 

Let's talk about it soon.
Thanks
Oliver

**Comment by flosse** [comment]
Hi Oliver,
thanks for your proposal! At the moment @ziedavid maintains this repository. I think he'll have a closer look at it in September :)
