### ISSUE TITLE
use anyhow & thiserror crates

### ISSUE THREAD

**Issue by flosse** [kartevonmorgen/openfairdb#66]

**Comment by flosse** [comment]
https://boats.gitlab.io/blog/post/2017-11-16-announcing-failure/

**Comment by flosse** [comment]
blocked by https://github.com/withoutboats/failure/issues/104

**Comment by uklotzde** [comment]
Blocked by (new link): https://github.com/rust-lang-nursery/failure/issues/104

**Comment by flosse** [comment]
[failure is deprecated now](https://github.com/rust-lang-nursery/failure/pull/347#issue-412484955) so we're going to use [anyhow](https://github.com/dtolnay/anyhow) and [thiserror](https://github.com/dtolnay/thiserror).

**Comment by flosse** [comment]
resolved in e981455557ebf82d4264fa766bde51515088afd4
