### ISSUE TITLE
Search: make tags searchable without "#"

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#80]
flosse/kartevonmorgen#297

when typing "foobar" the search should return entries with "foobar" in the Title, Description, and/or TAGS. When typing "#foobar" it should return only entries with "foobar" as a tag.

**Comment by wellemut** [comment]
Dear @uklotzde 
Please implement the search, that hastags are always included in the search, no matter if you use # or not!

Its a difficult questions but we have discussed it many times already. (https://github.com/flosse/kartevonmorgen/issues/297)

The best thing would be for **normal search**
1. List all search results that have the term in the title
2. List all search results, which have the term in description or tags
(So in this casehttps://kartevonmorgen.org/#/?center=48.980,7.207&zoom=4.00&search=%C3%96koligenta you should find much more than three items, becaus it is a popular tag https://kartevonmorgen.org/#/?center=48.980,7.207&zoom=4.00&search=%23%C3%96koligenta

For Filtering (#-search)
1. List **only** all items that have the tag!

In the past is has been like this allready

**Comment by uklotzde** [comment]
Fix committed.
