### ISSUE TITLE
Search: support AND and OR search

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#81]
The only thing that confuses me is, that tags in the searchfield have an AND connection and other terms and OR connection. We do not have any function yet, to have an OR connection of tags. But to equalize it, would be a good step someday, that

- "#term1, #term2" would result in an OR connection, all results need to have one of the terms
- the same OR connection for "term1, term2" which would search not only for tags, but also for text
- "#term1 #term2" would result in an AND connection, all results need to have both terms as tags.
- the same AND connection for "term1 term2", all results need to have both terms, eather as tag or as text.

A first solution was developed allready (https://github.com/kartevonmorgen/kartevonmorgen/issues/310#issuecomment-552411359) and is documented in https://blog.vonmorgen.org/iframes/#enhanced-search-function

**Comment by david-ziegler** [comment]
ah, the discussion about syntax is irrelevant for openfairdb. The API just has to be changed to support AND/OR for search. 
The only thing to decide is whether combinations of AND and OR should be implemented:
if not, the API request could be something like "search?text=foo,bar,baz&combination=AND
if yes, the API request could be along these lines: "search?text=(foo AND bar) OR (baz)"

**Comment by uklotzde** [comment]
The _text_ field of a search request is now parsed according to the [Tantivy query language](https://tantivy-search.github.io/tantivy/tantivy/query/struct.QueryParser.html).

But we should use this feature with care to avoid dependencies on implementation details! Actually the search text should better be escaped by the server to avoid injecting Tantivy queries directly. Currently this is not done and if _text_ contains an invalid Tantivy query the search request might fail.

**Comment by uklotzde** [comment]
Related to #86 and #82

**Comment by fulmicoton** [comment]
Sorry the tantivy doc is not up to date. Using AND and OR as keywords also work in the default query language.

**Comment by wellemut** [comment]
We can close this Issue in favor of this function: https://github.com/kartevonmorgen/kartevonmorgen/issues/310

**Comment by wellemut** [comment]
The only thing that confuses me is, that tags in the searchfield have an AND connection and other terms and OR connection. We do not have any function yet, to have an OR connection of tags. But to equalize it, would be a good step someday, that

- "#term1, #term2" would result in an OR connection, all results need to have one of the terms
- the same OR connection for "term1, term2" which would search not only for tags, but also for text
- "#term1 #term2" would result in an AND connection, all results need to have both terms as tags.
- the same AND connection for "term1 term2", all results need to have both terms, eather as tag or as text.

A first solution was developed allready (https://github.com/kartevonmorgen/kartevonmorgen/issues/310#issuecomment-552411359) and is documented in https://blog.vonmorgen.org/iframes/#enhanced-search-function

**Comment by wellemut** [comment]
> 
> 
> The _text_ field of a search request is now parsed according to the [Tantivy query language](https://tantivy-search.github.io/tantivy/tantivy/query/struct.QueryParser.html).
> 
> But we should use this feature with care to avoid dependencies on implementation details! Actually the search text should better be escaped by the server to avoid injecting Tantivy queries directly. Currently this is not done and if _text_ contains an invalid Tantivy query the search request might fail.

That means, we have to change the usability in the frontend? https://github.com/kartevonmorgen/kartevonmorgen/issues/617
