### ISSUE TITLE
Search: ignore "," in search

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#82]
currently "," in the search breaks it. Either use it as an "OR" connection between search words, or just ignore commas in the search.
see also #81

**Comment by uklotzde** [comment]
~~Should be fixed already on nightly after integrating the search engine in #86. Search texts should now be tokenized by white space and punctuation.~~ Unfortunately not fixed.

**Comment by uklotzde** [comment]
Unfortunately not fixed.

**Comment by uklotzde** [comment]
I've added a TODO with the URL of this bug in the test that would fail if uncommented.

**Comment by uklotzde** [comment]
Level is easy to moderate, depending on whether the search query needs to be adjusted or if only some pre-processing is needed.

**Comment by wellemut** [comment]
Comma in the search is just ignored. This issue can be closed.
