### ISSUE TITLE
Serverbreakdown

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#87]
@flosse @ziedavid 
Could it be, that our server is just too weak? Today it broke again.
Eather we get a bigger server or we optimize the map so that more action is done on client side....

**Comment by flosse** [comment]
Hm...that's interesting. It's the first time the server crashed. At the moment I cannot see what's the reason but it really shouldn't happen.

**Comment by flosse** [comment]
>Could it be, that our server is just too weak?

yes  indeed, but that's a matter of performance not a bug.

**Comment by flosse** [comment]
I just tried to crash the server with thousands of concurrent requests but it does not. I really can't break it. Nevertheless, I configured the service to restart the server if it would crash again.
So for now this is a quick fix but unless we can't reproduce the but we can't close this issue.

**Comment by flosse** [comment]
There is still no panic anymore! I'd really like to know what kind of edge-case leads to this error.
I'l close this issue for now until it occurs again.
