### ISSUE TITLE
Wrong Encoding in Emails

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#89]
Two types of emails have encoding errors: the email-confirmation-email and the email sent when an entry is changed. The new-entry-email is correct.

The subject of these emails sometimes (yes, not always) starts with "=?UTF-8?Q?Karte von Morgen: ..."

Also: "Karte von Morgen" should be "Karte von morgen"

**Comment by uklotzde** [comment]
https://github.com/flosse/kartevonmorgen/issues/321
