### ISSUE TITLE
Bug when registering

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#90]
to reproduce: register, then click on the link in the confirmation-email. The response of the request is "500: Internal Server Error".

**Comment by david-ziegler** [comment]
locally, registering works with v0.3.1.
But it doesn't work on kartevonmorgen.org

**Comment by flosse** [comment]
Does it work with a9716369cc57d1ce806e7089c56bf5cf51e197f2?

**Comment by david-ziegler** [comment]
yes. thanks :)
