### ISSUE TITLE
error when saving entry with duplicate tags

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#93]
when creating an entry and writing the same tag twice (e.g. "foo,bar,foo") one can't save the entry and it just says "internal server error". 2 possibilities: 
- ignore duplicate tags 
OR
- return a more meaningful error message

**Comment by flosse** [comment]
Thanks for reporting!

**Comment by flosse** [comment]
fixed in c26c42346d3702ec24fe8069f4e5622e137a94e0
