### ISSUE TITLE
API for FairDB

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/openfairdb#98]
It makes sense to document our API for others to access ist:

1. Hubs4Change / Stadtwandler Freiburg (Hannes Steinhilber)
2. Udo Wierlemann, Robert Faulstich (Wordpress-plugin für Ökoligenta.de)
2.1 Peter Hartmann und Steffen aus Leipzig https://projektwelt-zukunft.de/
3. Commons API (Commons Booking und Velogistics) https://docs.google.com/document/d/16mSeLw4UT7R1naQRG1C742MOiABuyrwRgaBgFmqN4FM/edit
4. Transition-Connect http://transition-connect.org/
5. OSM https://github.com/flosse/kartevonmorgen/issues/255
6. Communecter: https://github.com/flosse/kartevonmorgen/issues/342

**1. Hubs4Change**
> Kann man aktuell wie in GitHub geschrieben bereits per REST voll auf die Open Fair DB zugreifen? Kann das eigentlich jeder?
> Mit der API können wir dann auch die von Dubletten bereinigten Datensätze zu euch bringen.

**2. Udo**
> Hallo Helmut, hallo David,
> wie geht es euch? Ich hoffe gut :)
> selbst bin ich gerade mit Robert Faulstich dabei für Bobby Langer und Alander Baltosée ein Wordpress-Modul zu gestalten, in dem Organisationen und Unterstützerinnen des Wandels sich auf der Ökoligenta.de Seite mit Bild und Text (ein Statement zum Wandle) eintragen können und dann auf der Seite dargestellt werden sollen. Es ist angedacht dazu auch eine  Karte mit den Orten der UnterstützerInnen einzubinden. Dabei haben wir an eine Einbindung der "Karte von Morgen" gedacht, ähnlich wie bei Wechange.
 
> Meine  Frage ist nun, wie das technisch am besten funktionieren könnte, einen Abgleich der beiden Plattformen zu erreichen? Über die Seite http://bildungsagenten.org/kartevonmorgen/3/#Widget_zum_Einbetten habe ich schon recherchiert, mir ist aber aus dem dort Beschriebenen nicht klar, wie ich einen exklusiven Auszug für eine Gruppe von Menschen aus der Ökoligenta Seite bekommen könnte. Ich denke das es technisch ähnlich wie bei einer Wechange-Gruppe oder einem Wechange Projekt laufen müsste. Dort werden ja beispielsweise alle Mitglieder einer Gruppe angezeigt.

> Könntet ihr mir da weiterhelfen?
> Beste Grüße, Udo Wierlemann

**Comment by flosse** [comment]
This relates to #22

**Comment by flosse** [comment]
see https://github.com/kartevonmorgen/openfairdb/blob/master/openapi.yaml
