### ISSUE TITLE
Entry Image

### ISSUE THREAD

**Issue by david-ziegler** [kartevonmorgen/openfairdb#99]
I'd like to have two more fields in the `entry` data structure: 

`image_url`: the URL of an image for the entry
`image_link`: a URL that is followed when clicking on the image

so, whenever I POST, PUT, or GET an entry these two fields should be considered as well.

**Comment by uklotzde** [comment]
I propose to use a common suffix for both URL fields/columns to:
* `image_url`
* `image_link_url`
